repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/riverside-healthcare/djlint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.10
    hooks:
      - id: djhtml

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        files: .*\.html$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [
          "django-stubs",
          "types-PyYAML",
          "types-requests",
          "django-simple-history",
          "django-filter",
          "django-treebeard",
          "django-nested-admin",
          "django-environ",
          "django-htmx",
          "django-tailwind-cli",
          "django-widget-tweaks",
          "heroicons[django]"
        ]
        args: ["--config-file", "pyproject.toml"]

  - repo: https://github.com/fpgmaas/deptry
    rev: 0.24.0
    hooks:
      - id: deptry
        args: ["."]
