services:
  web:
    build: .
    container_name: baboom
    restart: always
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  celery:
    build: .
    command: celery -A baboom worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - DJANGO_SETTINGS_MODULE=baboom.settings
    depends_on:
      rabbitmq:
        condition: service_healthy
