sonar.exclusions=apps/api/**/migrations/**,apps/web/src/gql/**
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/models.py
