# Generated by Django 6.0 on 2026-01-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_manually_curated',
            new_name='is_published',
        ),
    ]
