# Generated by Django 6.0 on 2026-01-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_manually_curated_to_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
            ],
            options={
                'verbose_name': 'Alert Subscriber',
                'verbose_name_plural': 'Alert Subscribers',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If checked, this product will be visible on the public website.', verbose_name='Published'),
        ),
    ]
