# Generated by Django 6.0 on 2025-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manually_curated',
            field=models.BooleanField(default=False, help_text='If checked, the scraper will NOT update the name, description, or brand of this product.', verbose_name='Manually Curated'),
        ),
    ]
