# Generated by Django 6.0.1 on 2026-01-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nutritionfacts_serving_size_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='affiliate_link',
            field=models.URLField(blank=True, default='', help_text='URL with affiliate tracking parameters', verbose_name='Affiliate Tracking URL'),
        ),
    ]
