# Generated by Django 6.0 on 2025-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_is_manually_curated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='European Article Number / Global Trade Item Number', max_length=14, null=True, unique=True, verbose_name='EAN/GTIN'),
        ),
    ]
