"""How an OAuth client secret is stored.

A client secret is generated by the server, not chosen by a person: it is
long and uniformly random, so the work factor that protects a human password
buys nothing here. Django's default costs about a second per hash on the
deployment machine, which is most of the time a client registration takes.
"""

from django.contrib.auth.hashers import PBKDF2PasswordHasher


class ClientSecretHasher(PBKDF2PasswordHasher):
    """PBKDF2 at a work factor sized for a random secret, not a password."""

    algorithm = "oauth_pbkdf2_sha256"
    iterations = 30_000
