services:
  web:
    build: .
    container_name: baboom_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - ENABLE_API_DOCS=0
      - ALLOWED_HOSTS=*
    volumes:
      - ./media:/app/media
