## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = oci_license_manager_configuration.export_configuration.id
  is_repository_created_on_first_push = "true"
}

