## This configuration was generated by terraform-provider-oci

data oci_identity_availability_domain export_udwV-SA-SAOPAULO-1-AD-1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  ad_number      = "1"
}
