## This configuration was generated by terraform-provider-oci

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn-baboom {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name     = "Default DHCP Options for vcn-baboom"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.sa-saopaulo-1.aaaaaaaat3pxsx3tqzrdageah6ytq4evakzynlm3qfp6sp4tneaj2gothalq"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn11221833.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_Internet-Gateway-vcn-baboom {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:46.661Z"
  }
  display_name = "Internet Gateway vcn-baboom"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn-baboom.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn-baboom {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name = "Default Route Table for vcn-baboom"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.routetable.oc1.sa-saopaulo-1.aaaaaaaa7m52w4ul2o4wnohjzeptygjjh74x2q2zfqppxsjz7lphs54br37q"
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcn-baboom.id
    route_type        = "STATIC"
  }
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn-baboom {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name = "Default Security List for vcn-baboom"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = "ocid1.securitylist.oc1.sa-saopaulo-1.aaaaaaaa3a5nbuanmm25hgyb5dea2fbmjgwt2ina5awkjirf6vqeib3j47vq"
}

resource oci_core_vcn export_vcn-baboom {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name = "vcn-baboom"
  dns_label    = "vcn11221833"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_subnet export_subnet-baboom {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T22:03:31.170Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn-baboom.id
  display_name    = "subnet-baboom"
  dns_label       = "subnet11221903"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.0.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_default_route_table.export_Default-Route-Table-for-vcn-baboom.id
  security_list_ids = [
    oci_core_default_security_list.export_Default-Security-List-for-vcn-baboom.id,
  ]
  vcn_id = oci_core_vcn.export_vcn-baboom.id
}

resource oci_core_instance export_instance-backend-baboom {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "ENABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute RDMA GPU Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute HPC RDMA Auto-Configuration"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute HPC RDMA Authentication"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Cloud Guard Workload Protection"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--udwV-SA-SAOPAULO-1-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  #cluster_placement_group_id = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  #compute_cluster_id = <<Optional value not found in discovery>>
  create_vnic_details {
    #assign_ipv6ip = <<Optional value not found in discovery>>
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
      "Oracle-Tags.CreatedOn" = "2025-11-22T22:03:32.146Z"
    }
    display_name = "instance-backend-baboom"
    freeform_tags = {
    }
    hostname_label = "instance-backend-baboom"
    #ipv6address_ipv6subnet_cidr_pair_details = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip = "10.0.0.129"
    security_attributes = {
    }
    skip_source_dest_check = "false"
    #subnet_cidr = <<Optional value not found in discovery>>
    subnet_id = oci_core_subnet.export_subnet-baboom.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T22:03:32.004Z"
  }
  display_name = "instance-backend-baboom"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-1
  freeform_tags = {
  }
  #instance_configuration_id = <<Optional value not found in discovery>>
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_ai_enterprise_enabled = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "true"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  #launch_volume_attachments = <<Optional value not found in discovery>>
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5vNyCqQNPv2JkPw/qJaNZ/Dfxp4kjs70UDxwzYVDFL8a9H3rnyOpcw22OEyaCEfNtd52yAfTTWUR0Tf24aq6b+o/9hi/8lPfg4aI0frCi5EcCT42c4NDuKSgCgH1kj4ZsEUYDwqUoh9MFYWEKjWwW5wJ9heJW0/Ep8lvPreIMi7ii0YPf8ZB35+/t3N3HKLmnvr28AfXEPRVcsDDNQOtaOOWPEYkmGaObrDb+ZUB29/nmqxrsF7nJs76uJJ7FelXV+0a/WQ5xBYZQWP8Z6umWVMr9IA2T7LK3wHfE/U15SS6mDVJQPhuqXWcojeRJXJjG6jAsNL4jg17cLgrhZd+N ssh-key-2025-11-22"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  #preserve_data_volumes_created_at_launch = <<Optional value not found in discovery>>
  security_attributes = {
  }
  shape = "VM.Standard.E2.1.Micro"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "1"
    nvmes                     = "0"
    ocpus                     = "1"
    resource_management       = ""
    vcpus                     = "2"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    boot_volume_vpus_per_gb = "10"
    #instance_source_image_filter_details = <<Optional value not found in discovery>>
    #is_preserve_boot_volume_enabled = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_instance-backend-baboom
    source_type = "image"
  }
  state = "RUNNING"
  #update_operation_constraint = <<Optional value not found in discovery>>
}

resource oci_core_private_ip export_instance-backend-baboom_1 {
  cidr_prefix_length = "32"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T22:03:32.146Z"
  }
  display_name = "instance-backend-baboom"
  freeform_tags = {
  }
  hostname_label = "instance-backend-baboom"
  ip_address     = "10.0.0.129"
  #ipv4subnet_cidr_at_creation = <<Optional value not found in discovery>>
  lifetime = "EPHEMERAL"
  #route_table_id = <<Optional value not found in discovery>>
  subnet_id = oci_core_subnet.export_subnet-baboom.id
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.sa-saopaulo-1.abtxeljrk525ykjhbha7552z7nqrttduokyrp6nhlitl22uiw3f5r6mlunpa"
}

