## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_vcn-baboom_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name = "vcn-baboom"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_vcn-baboom_2 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  display_name = "vcn-baboom"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.sa-saopaulo-1.amaaaaaapfzlivaai23gx6mfx5zl7p5qjpd5gojoocbuuw5thxvivvlmmfba"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_subnet11221903-vcn11221833-oraclevcn-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T22:03:31.170Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "subnet11221903.vcn11221833.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_vcn-baboom_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_0-10-in-addr-arpa {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/rflemerson@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-11-22T21:33:45.829Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name      = "0.10.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_vcn-baboom_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_rrset export_subnet11221903-vcn11221833-oraclevcn-com_instance--backend--baboom-subnet11221903-vcn11221833-oraclevcn-com_A {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "instance-backend-baboom.subnet11221903.vcn11221833.oraclevcn.com"
  items {
    domain = "instance-backend-baboom.subnet11221903.vcn11221833.oraclevcn.com"
    rdata  = "10.0.0.129"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subnet11221903-vcn11221833-oraclevcn-com.id
}

resource oci_dns_rrset export_subnet11221903-vcn11221833-oraclevcn-com_subnet11221903-vcn11221833-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "subnet11221903.vcn11221833.oraclevcn.com"
  items {
    domain = "subnet11221903.vcn11221833.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subnet11221903-vcn11221833-oraclevcn-com.id
}

resource oci_dns_rrset export_subnet11221903-vcn11221833-oraclevcn-com_subnet11221903-vcn11221833-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "subnet11221903.vcn11221833.oraclevcn.com"
  items {
    domain = "subnet11221903.vcn11221833.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_subnet11221903-vcn11221833-oraclevcn-com.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_129-0-0-10-in--addr-arpa_PTR {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "129.0.0.10.in-addr.arpa"
  items {
    domain = "129.0.0.10.in-addr.arpa"
    rdata  = "instance-backend-baboom.subnet11221903.vcn11221833.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

