## This configuration was generated by terraform-provider-oci

resource oci_identity_policy export_Tenant-Admin-Policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Tenant Admin Policy"
  freeform_tags = {
  }
  name = "Tenant Admin Policy"
  statements = [
    "ALLOW GROUP Administrators to manage all-resources IN TENANCY",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_domain export_Default {
  #admin_email = <<Optional value not found in discovery>>
  #admin_first_name = <<Optional value not found in discovery>>
  #admin_last_name = <<Optional value not found in discovery>>
  #admin_user_name = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description  = "Default domain"
  display_name = "Default"
  freeform_tags = {
  }
  home_region        = "sa-saopaulo-1"
  is_hidden_on_login = "false"
  #is_notification_bypassed = <<Optional value not found in discovery>>
  #is_primary_email_required = <<Optional value not found in discovery>>
  license_type = "free"
  state        = "ACTIVE"
}

resource oci_identity_group export_Administrators {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Administrators"
  freeform_tags = {
  }
  name = "Administrators"
}

resource oci_identity_group export_All-Domain-Users {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "A group representing all users."
  freeform_tags = {
  }
  name = "All Domain Users"
}

resource oci_identity_user export_rflemerson-gmail-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "rflemerson@gmail.com"
  freeform_tags = {
  }
  name = "rflemerson@gmail.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_authentication_policy export_authentication_policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  network_policy {
    network_source_ids = [
    ]
  }
  password_policy {
    is_lowercase_characters_required = "true"
    is_numeric_characters_required   = "true"
    is_special_characters_required   = "false"
    is_uppercase_characters_required = "true"
    is_username_containment_allowed  = "false"
    minimum_password_length          = "12"
  }
}

resource oci_identity_ui_password export_rflemerson-gmail-com_ui_password {
  user_id = oci_identity_user.export_rflemerson-gmail-com.id
}

resource oci_identity_user_group_membership export_rflemerson-gmail-com_user_group_membership {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_rflemerson-gmail-com.id
}

