## This configuration was generated by terraform-provider-oci

resource oci_jms_utils_analyze_applications_configuration export_analyze_applications_configuration {
  #bucket = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  #namespace = <<Optional value not found in discovery>>
}

resource oci_jms_utils_subscription_acknowledgment_configuration export_subscription_acknowledgment_configuration {
  compartment_id  = oci_license_manager_configuration.export_configuration.id
  is_acknowledged = "false"
}

