## This configuration was generated by terraform-provider-oci

resource oci_license_manager_configuration export_configuration {
  compartment_id = "ocid1.tenancy.oc1..aaaaaaaavf6wkrobxic77lywhdtbmojb24ppkuavgi77piyy62y4irzjrmka"
  email_ids = [
  ]
}

