## This configuration was generated by terraform-provider-oci

resource oci_management_agent_management_agent export_Agent-instance-backend-baboom- {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "ocid1.managementagent.oc1.sa-saopaulo-1.amaaaaaapfzlivaasnlvbyrvkjiehbtdzd7oe6dqjwcgwwjxlnzntxoyfv3q"
    "Oracle-Tags.CreatedOn" = "2025-11-22T22:17:59.834Z"
  }
  #deploy_plugins_id = <<Optional value not found in discovery>>
  display_name = "Agent (instance-backend-baboom)"
  freeform_tags = {
  }
  managed_agent_id = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_agent_id]
  }
}

