## This configuration was generated by terraform-provider-oci

resource oci_recovery_protection_policy export_Platinum {
  backup_retention_period_in_days = "95"
  compartment_id                  = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #defined_tags = <<Optional value not found in discovery>>
  display_name = "Platinum"
  freeform_tags = {
  }
  must_enforce_cloud_locality = "false"
  #policy_locked_date_time = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [compartment_id]
  }
}

resource oci_recovery_protection_policy export_Gold {
  backup_retention_period_in_days = "65"
  compartment_id                  = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #defined_tags = <<Optional value not found in discovery>>
  display_name = "Gold"
  freeform_tags = {
  }
  must_enforce_cloud_locality = "false"
  #policy_locked_date_time = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [compartment_id]
  }
}

resource oci_recovery_protection_policy export_Silver {
  backup_retention_period_in_days = "35"
  compartment_id                  = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #defined_tags = <<Optional value not found in discovery>>
  display_name = "Silver"
  freeform_tags = {
  }
  must_enforce_cloud_locality = "false"
  #policy_locked_date_time = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [compartment_id]
  }
}

resource oci_recovery_protection_policy export_Bronze {
  backup_retention_period_in_days = "14"
  compartment_id                  = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #defined_tags = <<Optional value not found in discovery>>
  display_name = "Bronze"
  freeform_tags = {
  }
  must_enforce_cloud_locality = "false"
  #policy_locked_date_time = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [compartment_id]
  }
}

