# Generated by Django 6.0.8 on 2026-10-04 15:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('independent_store', 'Independent store'), ('marketplace', 'Marketplace'), ('app', 'App')], max_length=20, verbose_name='Kind')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('adapter', models.CharField(blank=True, help_text='The integration that reads it, e.g. vtex or shopify.', max_length=50, verbose_name='Adapter')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use an ISO 4217 code.')], verbose_name='Code')),
                ('minor_unit', models.PositiveSmallIntegerField(help_text='Decimal places a price is charged in: 2 for BRL, 0 for JPY.', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Minor Unit')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('kind', models.CharField(choices=[('acquirer', 'Acquirer'), ('wallet', 'Wallet'), ('issuer', 'Issuer'), ('gateway', 'Gateway'), ('card_network', 'Card network')], max_length=20, verbose_name='Kind')),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use an ISO 3166-1 alpha-2 code.')], verbose_name='Country')),
                ('timezone', models.CharField(help_text='IANA zone campaigns of this market are dated in.', max_length=64, verbose_name='Time Zone')),
                ('namespace', models.SlugField(help_text="Scopes external ids; the scraper's store slug for a store.", max_length=100, unique=True, verbose_name='Namespace')),
                ('provenance', models.CharField(choices=[('observed', 'Observed in the source'), ('source_contract', 'Declared by the source contract'), ('curated', 'Curated')], default='curated', help_text='How country and currency are known.', max_length=20, verbose_name='Provenance')),
                ('tax_inclusion', models.CharField(choices=[('included', 'Prices include every tax'), ('excluded', 'Taxes are charged on top'), ('unknown', 'Unknown')], default='unknown', help_text="Whether a shelf price already carries the market's taxes.", max_length=8, verbose_name='Taxes in prices')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='commerce.channel', verbose_name='Channel')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='commerce.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ('namespace',),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('seller', 'The seller'), ('channel', 'The channel'), ('third_party', 'A third party'), ('unknown', 'Unknown')], max_length=20, verbose_name='Kind')),
                ('label_raw', models.CharField(blank=True, max_length=100, verbose_name='Label as published')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_profiles', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Fulfillment Profile',
                'verbose_name_plural': 'Fulfillment Profiles',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('family', models.CharField(choices=[('card', 'Card'), ('instant_transfer', 'Instant transfer'), ('bank_slip', 'Bank slip'), ('wallet', 'Wallet'), ('deferred', 'Deferred payment'), ('store_credit', 'Store credit'), ('other', 'Other')], max_length=20, verbose_name='Family')),
                ('code', models.SlugField(verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.CharField(blank=True, help_text='Empty for a method used in every market.', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use an ISO 3166-1 alpha-2 code.')], verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('code', 'country'), name='unique_payment_method_per_country')],
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_id', models.CharField(blank=True, help_text='The seller id the market publishes; empty when it has none.', max_length=100, verbose_name='External ID')),
                ('name_raw', models.CharField(blank=True, max_length=200, verbose_name='Name as published')),
                ('is_channel_owner', models.BooleanField(default=False, help_text='The account of the store that runs the channel.', verbose_name='Channel owner')),
                ('resolution', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved')], default='resolved', max_length=10, verbose_name='Resolution')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_accounts', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Seller Account',
                'verbose_name_plural': 'Seller Accounts',
                'ordering': ('market', 'name_raw'),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('kind', models.CharField(choices=[('cashback', 'Cashback'), ('loyalty_points', 'Loyalty points'), ('membership', 'Membership'), ('subscription', 'Subscription'), ('card_benefit', 'Card benefit')], max_length=20, verbose_name='Kind')),
                ('issuer_name', models.CharField(blank=True, help_text='A bank, wallet or platform outside the catalog.', max_length=150, verbose_name='Issuer')),
                ('unit', models.CharField(help_text='A currency code, or the name of the points it grants.', max_length=50, verbose_name='Unit')),
                ('issuer_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='commerce.channel', verbose_name='Issuing channel')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='commerce.market', verbose_name='Market')),
                ('issuer_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='commerce.selleraccount', verbose_name='Issuing seller')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MerchantBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('evidence', models.TextField(help_text='What shows the account belongs to the merchant.', verbose_name='Evidence')),
                ('verified_at', models.DateTimeField(verbose_name='Verified At')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='commerce.merchant', verbose_name='Merchant')),
                ('seller_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_binding', to='commerce.selleraccount', verbose_name='Seller Account')),
            ],
            options={
                'verbose_name': 'Merchant Binding',
                'verbose_name_plural': 'Merchant Bindings',
            },
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('channel', 'country'), name='one_market_per_channel_country'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentprofile',
            constraint=models.UniqueConstraint(fields=('market', 'kind', 'label_raw'), name='unique_fulfillment_profile'),
        ),
        migrations.AddConstraint(
            model_name='selleraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('market', 'external_id'), name='unique_seller_external_id_per_market'),
        ),
        migrations.AddConstraint(
            model_name='selleraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_channel_owner', True)), fields=('market',), name='one_channel_owner_per_market'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('issuer_channel__isnull', False), ('issuer_seller__isnull', False), models.Q(('issuer_name', ''), _negated=True), _connector='OR'), name='program_has_an_issuer'),
        ),
    ]
