# Generated by Django 6.0.8 on 2026-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='tax_inclusion',
            field=models.CharField(choices=[('included', 'Prices include every tax'), ('excluded', 'Taxes are charged on top'), ('unknown', 'Unknown')], default='unknown', help_text="Whether a shelf price already carries the market's taxes.", max_length=8, verbose_name='Taxes in prices'),
        ),
    ]
