# Generated by Django 6.0.8 on 2026-10-04 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_seed_reference_data'),
        ('offers', '0007_typed_observations'),
        ('promotions', '0002_freeze_published_revisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.SlugField(verbose_name='Key')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('scenario', models.CharField(choices=[('listed', "The store's price"), ('cash', 'Paid at once'), ('payment', 'A payment method')], max_length=10, verbose_name='Scenario')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='Rules')),
                ('is_default', models.BooleanField(default=False, help_text='The scenario the public catalog ranks by when none is chosen.', verbose_name='Default ranking')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Content Hash')),
                ('market', models.ForeignKey(blank=True, help_text='Empty for a policy every market uses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Pricing Policy Revision',
                'verbose_name_plural': 'Pricing Policy Revisions',
                'ordering': ('key', '-number'),
            },
        ),
        migrations.CreateModel(
            name='OfferScenarioProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('priced', 'Priced'), ('no_price', 'No price in this scenario'), ('unavailable', 'Not purchasable')], max_length=12, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('explanation', models.JSONField(blank=True, default=dict, verbose_name='Explanation')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Fingerprint')),
                ('computed_at', models.DateTimeField(verbose_name='Computed At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='commerce.market', verbose_name='Market')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections', to='offers.offerpriceobservation', verbose_name='Observation')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='offers.offer', verbose_name='Offer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='pricing.pricingpolicyrevision', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Offer Scenario Projection',
                'verbose_name_plural': 'Offer Scenario Projections',
            },
        ),
        migrations.CreateModel(
            name='PricingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('input_fingerprint', models.CharField(max_length=64, verbose_name='Input Fingerprint')),
                ('engine_version', models.CharField(max_length=20, verbose_name='Engine Version')),
                ('snapshot', models.JSONField(help_text='Every input the engine read and the result it returned.', verbose_name='Snapshot')),
                ('merchandise_total', models.DecimalField(decimal_places=6, max_digits=19, null=True, verbose_name='Merchandise')),
                ('total_payable', models.DecimalField(decimal_places=6, max_digits=19, null=True, verbose_name='Total Payable')),
                ('evaluated_at', models.DateTimeField(verbose_name='Evaluated At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_quotes', to='commerce.market', verbose_name='Market')),
                ('observations', models.ManyToManyField(related_name='quotes', to='offers.offerpriceobservation', verbose_name='Observations read')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='pricing.pricingpolicyrevision', verbose_name='Policy')),
                ('revisions', models.ManyToManyField(related_name='quotes', to='promotions.promotionrevision', verbose_name='Revisions read')),
            ],
            options={
                'verbose_name': 'Pricing Quote',
                'verbose_name_plural': 'Pricing Quotes',
                'ordering': ('-evaluated_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Base Amount')),
                ('allocated_discount', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Allocated Discount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='offers.offer', verbose_name='Offer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.pricingquote', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Quote Line',
                'verbose_name_plural': 'Quote Lines',
            },
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group_fingerprint', models.CharField(max_length=64, verbose_name='Group Fingerprint')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('subdivision', models.CharField(blank=True, max_length=10, verbose_name='Subdivision')),
                ('postal_code_hash', models.CharField(max_length=64, verbose_name='Postal Code Hash')),
                ('modality', models.CharField(blank=True, max_length=100, verbose_name='Modality')),
                ('packages', models.JSONField(blank=True, default=list, verbose_name='Packages')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('estimate_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimate (days)')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('included_benefits', models.JSONField(blank=True, default=list, verbose_name='Included Benefits')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_quotes', to='commerce.selleraccount', verbose_name='Seller Account')),
            ],
            options={
                'verbose_name': 'Shipping Quote',
                'verbose_name_plural': 'Shipping Quotes',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='TaxFeeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group_fingerprint', models.CharField(max_length=64, verbose_name='Group Fingerprint')),
                ('kind', models.CharField(max_length=50, verbose_name='Kind')),
                ('base', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Base')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('inclusion', models.CharField(choices=[('included', 'Included in the price'), ('excluded', 'Charged on top'), ('unknown', 'Unknown')], max_length=8, verbose_name='Inclusion')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Tax or Fee Quote',
                'verbose_name_plural': 'Tax and Fee Quotes',
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversionQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=24, verbose_name='Rate')),
                ('spread', models.DecimalField(blank=True, decimal_places=6, help_text='Empty when unknown; unknown is not zero.', max_digits=9, null=True, verbose_name='Spread')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('observed_at', models.DateTimeField(verbose_name='Observed At')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='From')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='To')),
            ],
            options={
                'verbose_name': 'Currency Conversion Quote',
                'verbose_name_plural': 'Currency Conversion Quotes',
                'ordering': ('-observed_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='conversion_rate_positive'), models.CheckConstraint(condition=models.Q(('base', models.F('quote')), _negated=True), name='conversion_between_two_currencies')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricingpolicyrevision',
            constraint=models.UniqueConstraint(fields=('key', 'number'), name='unique_policy_revision'),
        ),
        migrations.AddIndex(
            model_name='offerscenarioprojection',
            index=models.Index(fields=['policy', 'status', 'amount'], name='pricing_off_policy__611603_idx'),
        ),
        migrations.AddIndex(
            model_name='offerscenarioprojection',
            index=models.Index(fields=['policy', 'expires_at'], name='pricing_off_policy__5081bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerscenarioprojection',
            constraint=models.UniqueConstraint(fields=('offer', 'policy'), name='one_projection_per_offer_policy'),
        ),
        migrations.AddConstraint(
            model_name='offerscenarioprojection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', False), ('status', 'priced')), models.Q(models.Q(('status', 'priced'), _negated=True), ('amount__isnull', True)), _connector='OR'), name='priced_projection_has_amount'),
        ),
        migrations.AddIndex(
            model_name='pricingquote',
            index=models.Index(fields=['input_fingerprint'], name='pricing_pri_input_f_9bc5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingquote',
            index=models.Index(fields=['group_fingerprint', '-observed_at'], name='pricing_shi_group_f_cb5bb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingquote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='shipping_amount_not_negative'),
        ),
    ]
