# Generated by Django 6.0.8 on 2026-10-04 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('offers', '0005_commercial_identity'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.SlugField(verbose_name='Key')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('scenario', models.CharField(choices=[('listed', "The store's price"), ('best', 'The best price paid now'), ('cash', 'Paid at once'), ('payment', 'A payment method')], max_length=10, verbose_name='Scenario')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='Rules')),
                ('is_default', models.BooleanField(default=False, help_text='The scenario the public catalog ranks by when none is chosen.', verbose_name='Default ranking')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Content Hash')),
                ('market', models.ForeignKey(blank=True, help_text='Empty for a policy every market uses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Pricing Policy Revision',
                'verbose_name_plural': 'Pricing Policy Revisions',
                'ordering': ('key', '-number'),
            },
        ),
        migrations.CreateModel(
            name='OfferScenarioProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('priced', 'Priced'), ('no_price', 'No price in this scenario'), ('unavailable', 'Not purchasable')], max_length=12, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('alternative', models.CharField(default='best', help_text="'best' is the winning combination; 'coupon', 'cashback' and 'cashback+coupon' are the best combinations using those benefits, kept so a filter never hides a valid option.", max_length=40, verbose_name='Alternative')),
                ('comparison_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('objective', models.CharField(default='items_payable', max_length=30)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('estimated_net_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('monetary_reward', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('uses_coupon', models.BooleanField(db_index=True, default=False)),
                ('has_cashback', models.BooleanField(db_index=True, default=False)),
                ('selected_route_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolved_url', models.URLField(blank=True, max_length=2000)),
                ('link_fixes_variant', models.BooleanField(default=False)),
                ('explanation', models.JSONField(blank=True, default=dict, verbose_name='Explanation')),
                ('link_fixes_seller', models.BooleanField(default=True, help_text="False when the offer's link may open another seller's offer.", verbose_name='Link opens this seller')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Fingerprint')),
                ('computed_at', models.DateTimeField(verbose_name='Computed At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='commerce.market', verbose_name='Market')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections', to='offers.offerpriceobservation', verbose_name='Observation')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='offers.offer', verbose_name='Offer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='pricing.pricingpolicyrevision', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Offer Scenario Projection',
                'verbose_name_plural': 'Offer Scenario Projections',
            },
        ),
        migrations.CreateModel(
            name='PricingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('input_fingerprint', models.CharField(max_length=64, verbose_name='Input Fingerprint')),
                ('engine_version', models.CharField(max_length=20, verbose_name='Engine Version')),
                ('snapshot', models.JSONField(help_text='Every input the engine read and the result it returned.', verbose_name='Snapshot')),
                ('merchandise_total', models.DecimalField(decimal_places=6, max_digits=19, null=True, verbose_name='Merchandise')),
                ('total_payable', models.DecimalField(decimal_places=6, max_digits=19, null=True, verbose_name='Total Payable')),
                ('evaluated_at', models.DateTimeField(verbose_name='Evaluated At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_quotes', to='commerce.market', verbose_name='Market')),
                ('observations', models.ManyToManyField(related_name='quotes', to='offers.offerpriceobservation', verbose_name='Observations read')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='pricing.pricingpolicyrevision', verbose_name='Policy')),
                ('revisions', models.ManyToManyField(related_name='quotes', to='promotions.promotionrevision', verbose_name='Revisions read')),
            ],
            options={
                'verbose_name': 'Pricing Quote',
                'verbose_name_plural': 'Pricing Quotes',
                'ordering': ('-evaluated_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('base_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Empty when the line had no price in the scenario.', max_digits=19, null=True, verbose_name='Base Amount')),
                ('allocated_discount', models.DecimalField(decimal_places=6, default=0, max_digits=19, verbose_name='Allocated Discount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='offers.offer', verbose_name='Offer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.pricingquote', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Quote Line',
                'verbose_name_plural': 'Quote Lines',
            },
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group_fingerprint', models.CharField(max_length=64, verbose_name='Group Fingerprint')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('subdivision', models.CharField(blank=True, max_length=10, verbose_name='Subdivision')),
                ('postal_code_hash', models.CharField(max_length=64, verbose_name='Postal Code Hash')),
                ('modality', models.CharField(blank=True, max_length=100, verbose_name='Modality')),
                ('external_quote_id', models.CharField(blank=True, help_text="The carrier's id for this quote, when it can be booked by id.", max_length=200, verbose_name='External Quote ID')),
                ('execution_guaranteed', models.BooleanField(default=False, help_text='The source honours this quote by id until it expires.', verbose_name='Execution guaranteed')),
                ('order_value', models.DecimalField(blank=True, decimal_places=6, help_text='The order value priced, when shipping depends on it.', max_digits=19, null=True, verbose_name='Order Value')),
                ('packages', models.JSONField(blank=True, default=list, verbose_name='Packages')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('estimate_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimate (days)')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('included_benefits', models.JSONField(blank=True, default=list, verbose_name='Included Benefits')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_quotes', to='commerce.selleraccount', verbose_name='Seller Account')),
            ],
            options={
                'verbose_name': 'Shipping Quote',
                'verbose_name_plural': 'Shipping Quotes',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='TaxFeeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group_fingerprint', models.CharField(max_length=64, verbose_name='Group Fingerprint')),
                ('kind', models.CharField(max_length=50, verbose_name='Kind')),
                ('charge_key', models.CharField(blank=True, help_text='Tells two charges of one kind apart; rereadings share it.', max_length=200, verbose_name='Charge Key')),
                ('covers_all_charges', models.BooleanField(default=False, help_text="The source answered for every charge of the group in this reading; a row of kind 'none' and amount 0 confirms there is none.", verbose_name='Covers every charge')),
                ('base', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Base')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Amount')),
                ('inclusion', models.CharField(choices=[('included', 'Included in the price'), ('excluded', 'Charged on top'), ('unknown', 'Unknown')], max_length=8, verbose_name='Inclusion')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Tax or Fee Quote',
                'verbose_name_plural': 'Tax and Fee Quotes',
            },
        ),
        migrations.AddConstraint(
            model_name='pricingpolicyrevision',
            constraint=models.UniqueConstraint(fields=('key', 'number'), name='unique_policy_revision'),
        ),
        migrations.AddIndex(
            model_name='offerscenarioprojection',
            index=models.Index(fields=['policy', 'status', 'amount'], name='pricing_off_policy__611603_idx'),
        ),
        migrations.AddIndex(
            model_name='offerscenarioprojection',
            index=models.Index(fields=['policy', 'expires_at'], name='pricing_off_policy__5081bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerscenarioprojection',
            constraint=models.UniqueConstraint(fields=('offer', 'policy', 'alternative'), name='one_projection_per_offer_policy_alternative'),
        ),
        migrations.AddConstraint(
            model_name='offerscenarioprojection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', False), ('status', 'priced')), models.Q(models.Q(('status', 'priced'), _negated=True), ('amount__isnull', True)), _connector='OR'), name='priced_projection_has_amount'),
        ),
        migrations.AddIndex(
            model_name='pricingquote',
            index=models.Index(fields=['input_fingerprint'], name='pricing_pri_input_f_9bc5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingquote',
            index=models.Index(fields=['group_fingerprint', '-observed_at'], name='pricing_shi_group_f_cb5bb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingquote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='shipping_amount_not_negative'),
        ),
    ]
