# Generated by Django 6.0.8 on 2026-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_hourly_projection_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='link_fixes_seller',
            field=models.BooleanField(default=True, help_text="False when the offer's link may open another seller's offer.", verbose_name='Link opens this seller'),
        ),
    ]
