# Generated by Django 6.0.8 on 2026-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_projection_link_fixes_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteline',
            name='allocated_discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19, verbose_name='Allocated Discount'),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Empty when the line had no price in the scenario.', max_digits=19, null=True, verbose_name='Base Amount'),
        ),
    ]
