# Generated by Django 6.0.8 on 2026-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_quote_line_without_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='link_fixes_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='resolved_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='selected_route_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='execution_guaranteed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='external_quote_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='taxfeequote',
            name='charge_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
