# Generated by Django 6.0.8 on 2026-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_offerscenarioprojection_link_fixes_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='comparison_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='estimated_net_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='has_cashback',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='monetary_reward',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='objective',
            field=models.CharField(default='items_payable', max_length=30),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='uses_coupon',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
