# Generated by Django 6.0.8 on 2026-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_offerscenarioprojection_comparison_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfeequote',
            name='covers_all_charges',
            field=models.BooleanField(default=False, help_text="The source answered for every charge of the group in this reading; a row of kind 'none' and amount 0 confirms there is none.", verbose_name='Covers every charge'),
        ),
        migrations.AlterField(
            model_name='taxfeequote',
            name='charge_key',
            field=models.CharField(blank=True, help_text='Tells two charges of one kind apart; rereadings share it.', max_length=200, verbose_name='Charge Key'),
        ),
    ]
