# Generated by Django 6.0.8 on 2026-10-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_market_tax_inclusion'),
        ('offers', '0008_price_confirmation'),
        ('pricing', '0008_fee_coverage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offerscenarioprojection',
            name='one_projection_per_offer_policy',
        ),
        migrations.AddField(
            model_name='offerscenarioprojection',
            name='alternative',
            field=models.CharField(default='best', help_text="'best' is the winning combination; 'coupon', 'cashback' and 'cashback+coupon' are the best combinations using those benefits, kept so a filter never hides a valid option.", max_length=40, verbose_name='Alternative'),
        ),
        migrations.AddConstraint(
            model_name='offerscenarioprojection',
            constraint=models.UniqueConstraint(fields=('offer', 'policy', 'alternative'), name='one_projection_per_offer_policy_alternative'),
        ),
    ]
