# Generated by Django 6.0.8 on 2026-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_projection_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingquote',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='The order value priced, when shipping depends on it.', max_digits=19, null=True, verbose_name='Order Value'),
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='execution_guaranteed',
            field=models.BooleanField(default=False, help_text='The source honours this quote by id until it expires.', verbose_name='Execution guaranteed'),
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='external_quote_id',
            field=models.CharField(blank=True, help_text="The carrier's id for this quote, when it can be booked by id.", max_length=200, verbose_name='External Quote ID'),
        ),
    ]
