"""Initial offers schema."""

# Generated by Django 6.0.3 on 2026-06-06 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial offers schema migration."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('store_slug', models.CharField(db_index=True, help_text='Raw store identifier as seen by the scraper', max_length=100, verbose_name='Store Slug')),
                ('external_id', models.CharField(db_index=True, help_text='Unique identifier in the store system (e.g., SKU)', max_length=100, verbose_name='Store Product ID')),
                ('name', models.CharField(blank=True, help_text='Product name as seen at the store', max_length=255, verbose_name='Name')),
                ('category', models.CharField(blank=True, help_text='Category/department as seen at the store', max_length=255, verbose_name='Category')),
                ('url', models.URLField(blank=True, help_text='Direct URL to the product page at the store', max_length=500, verbose_name='Product URL')),
                ('ean', models.CharField(blank=True, db_index=True, help_text='EAN/GTIN observed at the store, used for resolution', max_length=14, verbose_name='EAN/GTIN')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='SKU observed at the store', max_length=100, verbose_name='SKU')),
                ('pid', models.CharField(blank=True, help_text='Internal product id observed at the store', max_length=100, verbose_name='Product ID')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Latest observed price', max_digits=10, null=True, verbose_name='Current Price')),
                ('current_stock_status', models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', max_length=1, verbose_name='Current Stock Status')),
                ('current_stock_quantity', models.IntegerField(blank=True, help_text='Latest observed quantity in stock', null=True, verbose_name='Current Stock Quantity')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ('store_slug', 'external_id'),
                'indexes': [models.Index(fields=['store_slug', 'external_id'], name='offers_offe_store_s_b28adc_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_slug', 'external_id'), name='unique_offer_identity')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock_status', models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', max_length=1, verbose_name='Stock Status')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Observed At')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='offers.offer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Price Observation',
                'verbose_name_plural': 'Price Observations',
                'ordering': ('-observed_at',),
                'get_latest_by': 'observed_at',
                'indexes': [models.Index(fields=['offer', '-observed_at'], name='offers_pric_offer_i_ba37b6_idx'), models.Index(fields=['stock_status'], name='offers_pric_stock_s_24acee_idx')],
            },
        ),
    ]
