# Generated by Django 6.0.8 on 2026-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delisted_at',
            field=models.DateTimeField(blank=True, help_text='When the unit stopped appearing on a page that did list it', null=True, verbose_name='Delisted At'),
        ),
        migrations.AddField(
            model_name='offer',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the store last published this unit', null=True, verbose_name='Last Seen At'),
        ),
    ]
