# Generated by Django 6.0.8 on 2026-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_delisted_at_offer_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='missed_runs',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive successful store runs that did not publish this unit', verbose_name='Missed Runs'),
        ),
    ]
