# Generated by Django 6.0.8 on 2026-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_missed_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delisted_reason',
            field=models.CharField(blank=True, choices=[('gone', 'The store stopped publishing it'), ('superseded', 'Replaced by offers for each buyable variant')], default='', max_length=20, verbose_name='Delisted Reason'),
        ),
        migrations.AddField(
            model_name='offer',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Options the store published for this unit, verbatim: a list of {"name", "value"} such as {"name": "Sabor", "value": "Chocolate"}.', verbose_name='Options'),
        ),
    ]
