# Generated by Django 6.0.8 on 2026-10-03 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('offers', '0004_offer_options_and_delist_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fulfillment_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='commerce.fulfillmentprofile', verbose_name='Fulfillment Profile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('unknown', 'Unknown')], default='unknown', max_length=12, verbose_name='Item Condition'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller_account',
            field=models.ForeignKey(blank=True, help_text='Empty while the source has not said who sells it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='commerce.selleraccount', verbose_name='Seller Account'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_id', models.CharField(help_text='The product or advertisement id the market publishes.', max_length=100, verbose_name='External ID')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('catalog_product_id', models.CharField(blank=True, help_text="The channel's own catalog id, such as an ASIN.", max_length=100, verbose_name='Channel catalog ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ('market', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='ListingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_id', models.CharField(max_length=100, verbose_name='External ID')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options as published: a list of {"name", "value"}.', verbose_name='Options')),
                ('selection', models.JSONField(blank=True, default=dict, help_text='How the unit is selected on its page, as the adapter knows.', verbose_name='Selection')),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='GTIN')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='offers.listing', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Listing Variant',
                'verbose_name_plural': 'Listing Variants',
                'ordering': ('listing', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='FeaturedOfferObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_observations', to='offers.offer', verbose_name='Offer')),
                ('listing_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_observations', to='offers.listingvariant', verbose_name='Listing Variant')),
            ],
            options={
                'verbose_name': 'Featured Offer Observation',
                'verbose_name_plural': 'Featured Offer Observations',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='listing_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offers.listingvariant', verbose_name='Listing Variant'),
        ),
        migrations.CreateModel(
            name='OfferSourceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('namespace', models.SlugField(max_length=100, verbose_name='Namespace')),
                ('scheme', models.SlugField(verbose_name='Scheme')),
                ('scheme_version', models.PositiveSmallIntegerField(default=1, verbose_name='Scheme Version')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_identities', to='offers.offer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Offer Source Identity',
                'verbose_name_plural': 'Offer Source Identities',
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('market', 'external_id'), name='unique_listing_per_market'),
        ),
        migrations.AddConstraint(
            model_name='listingvariant',
            constraint=models.UniqueConstraint(fields=('listing', 'external_id'), name='unique_variant_per_listing'),
        ),
        migrations.AddIndex(
            model_name='featuredofferobservation',
            index=models.Index(fields=['listing_variant', '-observed_at'], name='offers_feat_listing_1f7ffb_idx'),
        ),
        migrations.AddConstraint(
            model_name='offersourceidentity',
            constraint=models.UniqueConstraint(fields=('namespace', 'scheme', 'scheme_version', 'key'), name='unique_offer_source_identity'),
        ),
    ]
