# Generated by Django 6.0.8 on 2026-10-04 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('offers', '0004_offer_options_and_delist_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('catalog_response', 'Catalog response'), ('cart_quote', 'Cart quote'), ('product_page', 'Product page'), ('regulation', 'Regulation'), ('announcement', 'Announcement'), ('theme_setting', 'Theme setting'), ('manual', 'Manual reading')], max_length=20, verbose_name='Kind')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Source URL')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('excerpt', models.TextField(blank=True, help_text='The words that prove it, verbatim; never a whole page.', verbose_name='Excerpt')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Content Hash')),
                ('captured_by', models.CharField(blank=True, help_text='The adapter, or the curator who read it.', max_length=100, verbose_name='Captured By')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='fulfillment_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='commerce.fulfillmentprofile', verbose_name='Fulfillment Profile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('unknown', 'Unknown')], default='unknown', max_length=12, verbose_name='Item Condition'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller_account',
            field=models.ForeignKey(blank=True, help_text='Empty while the source has not said who sells it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='commerce.selleraccount', verbose_name='Seller Account'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='current_stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock'), ('P', 'Pre-order'), ('B', 'Backorder'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='Current Stock Status'),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock'), ('P', 'Pre-order'), ('B', 'Backorder'), ('U', 'Unknown')], default='A', max_length=1, verbose_name='Stock Status'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_id', models.CharField(help_text='The product or advertisement id the market publishes.', max_length=100, verbose_name='External ID')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('catalog_product_id', models.CharField(blank=True, help_text="The channel's own catalog id, such as an ASIN.", max_length=100, verbose_name='Channel catalog ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ('market', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='ListingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_id', models.CharField(max_length=100, verbose_name='External ID')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options as published: a list of {"name", "value"}.', verbose_name='Options')),
                ('selection', models.JSONField(blank=True, default=dict, help_text='How the unit is selected on its page, as the adapter knows.', verbose_name='Selection')),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='GTIN')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='offers.listing', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Listing Variant',
                'verbose_name_plural': 'Listing Variants',
                'ordering': ('listing', 'external_id'),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='listing_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offers.listingvariant', verbose_name='Listing Variant'),
        ),
        migrations.CreateModel(
            name='ObservationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('adapter', models.CharField(max_length=50, verbose_name='Adapter')),
                ('adapter_version', models.CharField(max_length=20, verbose_name='Adapter Version')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10, verbose_name='Status')),
                ('request_context', models.JSONField(blank=True, default=dict, help_text='Endpoint, region, sales channel and a hash of any postal code; never a personal value in clear.', verbose_name='Request Context')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_batches', to='commerce.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Observation Batch',
                'verbose_name_plural': 'Observation Batches',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedOfferObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_observations', to='offers.offer', verbose_name='Offer')),
                ('listing_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_observations', to='offers.listingvariant', verbose_name='Listing Variant')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='featured_offers', to='offers.observationbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Featured Offer Observation',
                'verbose_name_plural': 'Featured Offer Observations',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='CollectionCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('dimension', models.CharField(choices=[('variants', 'Variants'), ('sellers', 'Sellers'), ('offers', 'Offers'), ('payment_prices', 'Payment prices'), ('availability', 'Availability'), ('pagination', 'Pagination')], max_length=20, verbose_name='Dimension')),
                ('partition', models.CharField(help_text='What was enumerated: a listing id, a category, a page range.', max_length=255, verbose_name='Partition')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed'), ('access_unavailable', 'Access unavailable')], max_length=20, verbose_name='Status')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('cursor', models.CharField(blank=True, help_text='Where enumeration stopped, when the source pages it.', max_length=255, verbose_name='Cursor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='offers.observationbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Collection Coverage',
                'verbose_name_plural': 'Collection Coverage',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock'), ('P', 'Pre-order'), ('B', 'Backorder'), ('U', 'Unknown')], max_length=1, verbose_name='Status')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('destination', models.JSONField(blank=True, default=dict, verbose_name='Destination')),
                ('source_field', models.CharField(blank=True, max_length=100, verbose_name='Source Field')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_points', to='offers.offer', verbose_name='Offer')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availability_points', to='offers.observationbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Availability Observation',
                'verbose_name_plural': 'Availability Observations',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='OfferPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Amount')),
                ('amount_basis', models.CharField(choices=[('unit', 'One unit'), ('line', 'A line'), ('order', 'An order')], default='unit', max_length=5, verbose_name='Amount Basis')),
                ('role', models.CharField(choices=[('payable', 'Payable'), ('reference', 'Reference')], max_length=10, verbose_name='Role')),
                ('capture_stage', models.CharField(choices=[('catalog', 'Catalog'), ('product_page', 'Product page'), ('cart', 'Cart'), ('checkout', 'Checkout')], default='catalog', max_length=15, verbose_name='Capture Stage')),
                ('evidence_level', models.CharField(choices=[('advertised', 'Advertised'), ('observed_in_catalog', 'Observed in catalog'), ('quoted_for_context', 'Quoted for a context')], default='observed_in_catalog', max_length=20, verbose_name='Evidence Level')),
                ('semantics', models.CharField(choices=[('known', 'Known'), ('legacy_unknown', 'Legacy, meaning unknown')], default='known', max_length=15, verbose_name='Semantics')),
                ('payment_scope', models.CharField(choices=[('unknown', 'Unknown'), ('any', 'Any method'), ('cash', 'Paid at once, method not named'), ('method', 'A named method')], default='unknown', max_length=10, verbose_name='Payment Scope')),
                ('payment_provider_raw', models.CharField(blank=True, max_length=100, verbose_name='Payment provider as published')),
                ('payment_label_raw', models.CharField(blank=True, max_length=100, verbose_name='Payment label as published')),
                ('installment_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Installments')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Installment Amount')),
                ('interest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', help_text='Whether the installments carry interest.', max_length=7, verbose_name='Interest')),
                ('quantity_min', models.PositiveIntegerField(default=1, verbose_name='Minimum Quantity')),
                ('quantity_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Quantity')),
                ('condition_key', models.CharField(db_index=True, help_text='Hash of the normalized context; never amount or time.', max_length=64, verbose_name='Condition Key')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Membership, destination and other conditions, typed.', verbose_name='Context')),
                ('tax_inclusion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7, verbose_name='Tax Included')),
                ('source_field', models.CharField(max_length=100, verbose_name='Source Field')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observed At')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recorded At')),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The last read that stated this value.', verbose_name='Confirmed At')),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='The first complete read that no longer stated this condition.', null=True, verbose_name='Withdrawn At')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('fresh_until', models.DateTimeField(blank=True, null=True, verbose_name='Fresh Until')),
                ('composition', models.CharField(choices=[('known', 'Known'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=7, verbose_name='Composition')),
                ('included_adjustments', models.JSONField(blank=True, default=list, help_text='What the value already includes: [{"kind", "amount", ...}].', verbose_name='Included Adjustments')),
                ('derivation', models.CharField(blank=True, help_text='How a derived value was computed, e.g. advertised_rate.', max_length=30, verbose_name='Derivation')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_points', to='offers.observationbatch', verbose_name='Batch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivations', to='offers.offerpriceobservation', verbose_name='Derived From')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_points', to='offers.evidence', verbose_name='Evidence')),
                ('listing_variant', models.ForeignKey(blank=True, help_text='A price the source states without naming a seller.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_price_points', to='offers.listingvariant', verbose_name='Listing Variant')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='offers.offer', verbose_name='Offer')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Offer Price Observation',
                'verbose_name_plural': 'Offer Price Observations',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='OfferSourceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('namespace', models.SlugField(max_length=100, verbose_name='Namespace')),
                ('scheme', models.SlugField(verbose_name='Scheme')),
                ('scheme_version', models.PositiveSmallIntegerField(default=1, verbose_name='Scheme Version')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_identities', to='offers.offer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Offer Source Identity',
                'verbose_name_plural': 'Offer Source Identities',
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('market', 'external_id'), name='unique_listing_per_market'),
        ),
        migrations.AddConstraint(
            model_name='listingvariant',
            constraint=models.UniqueConstraint(fields=('listing', 'external_id'), name='unique_variant_per_listing'),
        ),
        migrations.AddIndex(
            model_name='featuredofferobservation',
            index=models.Index(fields=['listing_variant', '-observed_at'], name='offers_feat_listing_1f7ffb_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectioncoverage',
            constraint=models.UniqueConstraint(fields=('batch', 'dimension', 'partition'), name='unique_coverage_per_batch_dimension_partition'),
        ),
        migrations.AddIndex(
            model_name='availabilityobservation',
            index=models.Index(fields=['offer', '-observed_at'], name='offers_avai_offer_i_4afae9_idx'),
        ),
        migrations.AddIndex(
            model_name='offerpriceobservation',
            index=models.Index(fields=['offer', 'condition_key', '-observed_at'], name='offers_offe_offer_i_a23acb_idx'),
        ),
        migrations.AddIndex(
            model_name='offerpriceobservation',
            index=models.Index(fields=['listing_variant', 'condition_key', '-observed_at'], name='offers_offe_listing_9f0c23_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerpriceobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('listing_variant__isnull', True), ('offer__isnull', False)), models.Q(('listing_variant__isnull', False), ('offer__isnull', True)), _connector='OR'), name='price_point_has_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='offerpriceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='price_point_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='offerpriceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__isnull', True), ('payment_scope', 'method'), _connector='OR'), name='price_point_method_only_with_method_scope'),
        ),
        migrations.AddConstraint(
            model_name='offerpriceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('derived_from__isnull', True), models.Q(('derivation', ''), _negated=True), _connector='OR'), name='price_point_derivation_named'),
        ),
        migrations.AddConstraint(
            model_name='offersourceidentity',
            constraint=models.UniqueConstraint(fields=('namespace', 'scheme', 'scheme_version', 'key'), name='unique_offer_source_identity'),
        ),
    ]
