# Generated by Django 6.0.8 on 2026-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_commercial_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='current_stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock'), ('P', 'Pre-order'), ('B', 'Backorder'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='Current Stock Status'),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock'), ('P', 'Pre-order'), ('B', 'Backorder'), ('U', 'Unknown')], default='A', max_length=1, verbose_name='Stock Status'),
        ),
    ]
