# Generated by Django 6.0.8 on 2026-10-04 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_typed_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpriceobservation',
            name='confirmed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The last read that stated this value.', verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='offerpriceobservation',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='The first complete read that no longer stated this condition.', null=True, verbose_name='Withdrawn At'),
        ),
    ]
