# Generated by Django 6.0.8 on 2026-09-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeditemextraction',
            name='scraped_item',
        ),
        migrations.RemoveField(
            model_name='scrapeditemextraction',
            name='source_page',
        ),
        migrations.RemoveIndex(
            model_name='scrapeditem',
            name='scrapers_sc_status_99bac4_idx',
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='offer',
            field=models.OneToOneField(help_text='Offer observed by the scraper', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_item', to='offers.offer', verbose_name='Merchant Offer'),
        ),
        migrations.DeleteModel(
            name='ScrapedItemExtraction',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='last_attempt_at',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='last_error_log',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='status',
        ),
    ]
