# Generated by Django 6.0.3 on 2026-06-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='http_etag',
            field=models.CharField(blank=True, help_text='Last ETag seen for the product HTML, for conditional GETs', max_length=250),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='http_last_modified',
            field=models.CharField(blank=True, help_text='Last Last-Modified seen for the product HTML', max_length=100),
        ),
    ]
