# Generated by Django 6.0.3 on 2026-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpage',
            name='http_etag',
        ),
        migrations.RemoveField(
            model_name='scrapedpage',
            name='http_last_modified',
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Full rendered product-page HTML — the capture source of truth'),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='response_meta',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP response metadata for the capture (status, headers)'),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='html_structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Schema.org metadata (JSON-LD, microdata, ...) parsed from the HTML'),
        ),
    ]
