# Generated by Django 6.0.8 on 2026-09-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_remove_scrapeditemextraction_scraped_item_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrapedpage',
            name='scrapers_sc_store_s_d918a4_idx',
        ),
    ]
