# Generated by Django 6.0.1 on 2026-02-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_historicalscrapeditem_error_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscrapeditem',
            name='product_link',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='product_link',
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_slug', models.CharField(db_index=True, help_text='Store identifier', max_length=100)),
                ('url', models.URLField(help_text='Page URL', max_length=500, unique=True)),
                ('raw_content', models.TextField(blank=True, default='', help_text='Raw HTML or JSON content')),
                ('content_type', models.CharField(choices=[('HTML', 'HTML'), ('JSON', 'JSON')], default='HTML', max_length=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['url'], name='scrapers_sc_url_51f90d_idx'), models.Index(fields=['store_slug', 'url'], name='scrapers_sc_store_s_d918a4_idx')],
            },
        ),
        migrations.AddField(
            model_name='historicalscrapeditem',
            name='source_page',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Source page where this item was found', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrapers.scrapedpage'),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='source_page',
            field=models.ForeignKey(blank=True, help_text='Source page where this item was found', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scrapers.scrapedpage'),
        ),
    ]
