# Generated by Django 6.0.8 on 2026-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_drop_page_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='variant_context',
            field=models.JSONField(blank=True, default=dict, help_text="Which unit of the source page this offer is, in the store's words"),
        ),
    ]
