# Generated by Django 6.0.3 on 2026-03-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_remove_historicalscrapeditem_product_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenFoodFactsData',
        ),
    ]
