# Generated by Django 6.0.8 on 2026-10-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_commercial_identity'),
        ('scrapers', '0003_add_variant_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='The listing this crawl evidence describes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_pages', to='offers.listing'),
        ),
    ]
