# Generated by Django 6.0.3 on 2026-04-18 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_scrapedpage_api_context_and_html_structured_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItemExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_report', models.TextField(blank=True, help_text='Ordered text report extracted from product images')),
                ('extracted_product', models.JSONField(blank=True, default=dict, help_text='Recursive product tree returned by the agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_item', models.OneToOneField(help_text='Scraped item that produced this extraction', on_delete=django.db.models.deletion.CASCADE, related_name='agent_extraction', to='scrapers.scrapeditem')),
                ('source_page', models.ForeignKey(help_text='Source page used by the agent pipeline', on_delete=django.db.models.deletion.CASCADE, related_name='agent_extractions', to='scrapers.scrapedpage')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
