# Generated by Django 6.0.3 on 2026-04-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_nutrient_sources_alter_brand_options_and_more'),
        ('scrapers', '0006_scrapeditemextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditemextraction',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this extraction was approved into the catalog', null=True),
        ),
        migrations.AddField(
            model_name='scrapeditemextraction',
            name='approved_product',
            field=models.ForeignKey(blank=True, help_text='Catalog product created from this extraction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraper_extractions', to='core.product'),
        ),
    ]
