"""Alter scraped item status choices to support manual Dagster queueing."""

# Generated by Django 6.0.3 on 2026-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update current and historical scraped item status field choices."""

    dependencies = [
        ('scrapers', '0008_scraperrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscrapeditem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued for Agents'), ('processing', 'Processing'), ('linked', 'Linked'), ('error', 'Error (Retry)'), ('discarded', 'Discarded (Junk)'), ('review', 'Needs Review'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued for Agents'), ('processing', 'Processing'), ('linked', 'Linked'), ('error', 'Error (Retry)'), ('discarded', 'Discarded (Junk)'), ('review', 'Needs Review'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20),
        ),
    ]
