upstream api_app {
    server api:8000;
}

upstream web_app {
    server web:80;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    location /media/ {
        alias /app/media/;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /graphql/ {
        proxy_pass http://api_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_redirect off;
    }

    location /admin/ {
        proxy_pass http://api_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://web_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_redirect off;
    }
}
