# Generated by Django 6.0 on 2025-12-29 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_slug', models.CharField(db_index=True, help_text='Store identifier', max_length=100)),
                ('external_id', models.CharField(db_index=True, help_text='Unique ID from Store', max_length=100)),
                ('product_link', models.URLField(blank=True, help_text='URL to product page', max_length=500)),
                ('name', models.CharField(blank=True, help_text='Name extracted from source', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Category/Department extracted from source', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Available quantity in stock', null=True)),
                ('stock_status', models.CharField(blank=True, choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', max_length=1)),
                ('pid', models.CharField(blank=True, help_text='Product ID extracted from source', max_length=100)),
                ('ean', models.CharField(blank=True, db_index=True, help_text='EAN/GTIN extracted from source', max_length=14)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='SKU extracted from source', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('linked', 'Linked'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_items', to='core.productstore')),
            ],
            options={
                'indexes': [models.Index(fields=['store_slug', 'external_id'], name='scrapers_sc_store_s_a44af4_idx'), models.Index(fields=['status'], name='scrapers_sc_status_99bac4_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_slug', 'external_id'), name='unique_scraped_item_identity')],
            },
        ),
    ]
