# Generated by Django 6.0 on 2025-12-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('store', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('linked', 'Linked'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_items', to='core.productstore')),
            ],
        ),
    ]
