# Generated by Django 6.0 on 2025-12-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_product_is_manually_curated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Product URL')),
                ('store', models.CharField(max_length=100, verbose_name='Store Name')),
                ('external_id', models.CharField(max_length=100, verbose_name='External ID')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Raw Data')),
                ('status', models.CharField(choices=[('new', 'New (Pending)'), ('linked', 'Linked (Active)'), ('ignored', 'Ignored')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_items', to='core.productstore', verbose_name='Linked Product')),
            ],
            options={
                'verbose_name': 'Scraped Item',
                'verbose_name_plural': 'Scraped Items',
                'indexes': [models.Index(fields=['store', 'external_id'], name='scrapers_sc_store_cb4d77_idx'), models.Index(fields=['status'], name='scrapers_sc_status_99bac4_idx')],
            },
        ),
    ]
