# Generated by Django 6.0 on 2025-12-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFoodFactsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, help_text='European Article Number / GTIN', max_length=14, unique=True, verbose_name='EAN')),
                ('raw_data', models.JSONField(blank=True, help_text='Full JSON response from Open Food Facts API', null=True, verbose_name='Raw Open Food Facts Data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Open Food Facts Data',
                'verbose_name_plural': 'Open Food Facts Data',
            },
        ),
    ]
