# Generated by Django 6.0 on 2025-12-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='EAN/GTIN extracted from source', max_length=14, null=True),
        ),
    ]
