# Generated by Django 6.0 on 2025-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_scrapeditem_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU extracted from source', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='ean',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EAN/GTIN extracted from source', max_length=14),
            preserve_default=False,
        ),
    ]
