# Generated by Django 6.0 on 2025-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_ean'),
        ('scrapers', '0003_scrapeditem_sku_alter_scrapeditem_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='scrapeditem',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='unique_store_sku'),
        ),
    ]
