# Generated by Django 6.0 on 2025-12-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_ean'),
        ('scrapers', '0004_alter_scrapeditem_url_scrapeditem_unique_store_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scrapeditem',
            name='unique_store_sku',
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AddConstraint(
            model_name='scrapeditem',
            constraint=models.UniqueConstraint(fields=('store', 'external_id'), name='unique_scraped_item_store_external_id'),
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='sku',
        ),
    ]
