# Generated by Django 6.0 on 2025-12-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_ean'),
        ('scrapers', '0005_remove_scrapeditem_unique_store_sku_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scrapeditem',
            name='unique_scraped_item_store_external_id',
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU/Variant ID extracted from source', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='scrapeditem',
            constraint=models.UniqueConstraint(fields=('store', 'external_id', 'sku'), name='unique_scraped_item_composite_key'),
        ),
    ]
