# Generated by Django 6.0 on 2025-12-07 19:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Brand description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Unique category name', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Flavor description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Store description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Unique tag name', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Tag description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('weight', models.PositiveIntegerField(help_text='Total product weight in grams', verbose_name='Weight (grams)')),
                ('packaging', models.CharField(choices=[('REFILL', 'Refill Package'), ('CONTAINER', 'Container Package')], max_length=20, verbose_name='Packaging Type')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductNutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavors', models.ManyToManyField(blank=True, help_text='Flavors associated with this nutritional profile', to='core.flavor', verbose_name='Flavors')),
                ('product', models.ForeignKey(help_text='Product associated with this nutritional profile', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Base Product')),
            ],
            options={
                'verbose_name': 'Product Nutrition Profile',
                'verbose_name_plural': 'Product Nutrition Profiles',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('serving_size_grams', models.PositiveSmallIntegerField(verbose_name='Serving Size (g)')),
                ('energy_kcal', models.PositiveSmallIntegerField(verbose_name='Energy Content (kcal)')),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carbohydrates (g)')),
                ('total_sugars', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Sugars (g)')),
                ('added_sugars', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Added Sugars (g)')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protein Content (g)')),
                ('total_fats', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Fats (g)')),
                ('saturated_fats', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Saturated Fats (g)')),
                ('trans_fats', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Trans Fats (g)')),
                ('dietary_fiber', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Dietary Fiber (g)')),
                ('sodium', models.PositiveIntegerField(verbose_name='Sodium Content (mg)')),
                ('product_profile', models.ForeignKey(help_text='Product profile associated with this nutritional information', on_delete=django.db.models.deletion.CASCADE, to='core.productnutritionprofile', verbose_name='Product Nutrition Profile')),
            ],
            options={
                'verbose_name': 'Nutritional Information',
                'verbose_name_plural': 'Nutritional Information tables',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Unique identifier in store system (e.g., SKU)', max_length=100, verbose_name='Store Product ID')),
                ('product_link', models.URLField(help_text='Direct URL to product page in the store', verbose_name='Store Product URL')),
                ('affiliate_link', models.URLField(blank=True, help_text='URL with affiliate tracking parameters', null=True, verbose_name='Affiliate Tracking URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Related Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Associated Store')),
            ],
            options={
                'verbose_name': 'Store Product Link',
                'verbose_name_plural': 'Store Product Links',
                'ordering': ['store__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10, verbose_name='Current Price')),
                ('stock_status', models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', help_text='Current availability status', max_length=1, verbose_name='Inventory Status')),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='Automatic timestamp when record was created', verbose_name='Collection Timestamp')),
                ('store_product_link', models.ForeignKey(help_text='Link to specific product-store combination', on_delete=django.db.models.deletion.CASCADE, to='core.productstore', verbose_name='Store Product Link')),
            ],
            options={
                'verbose_name': 'Price Tracking Record',
                'verbose_name_plural': 'Price Tracking Records',
                'ordering': ['-collected_at'],
                'get_latest_by': 'collected_at',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductPriceHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10, verbose_name='Current Price')),
                ('stock_status', models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', help_text='Current availability status', max_length=1, verbose_name='Inventory Status')),
                ('collected_at', models.DateTimeField(blank=True, editable=False, help_text='Automatic timestamp when record was created', verbose_name='Collection Timestamp')),
                ('history_change_reason', models.TextField(blank=True, null=True, verbose_name='Change Reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store_product_link', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to specific product-store combination', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.productstore', verbose_name='Store Product Link')),
            ],
            options={
                'verbose_name': 'Version History',
                'verbose_name_plural': 'historical Price Tracking Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, through='core.ProductStore', to='core.store', verbose_name='Available In Stores'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag', verbose_name='Product Tags'),
        ),
        migrations.CreateModel(
            name='AdditionalNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Vitamin C, Iron, Zinc', max_length=100, verbose_name='Nutrient Name')),
                ('value', models.DecimalField(decimal_places=3, help_text='Measured amount per serving', max_digits=10, verbose_name='Nutrient Quantity')),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('mg', 'Milligrams'), ('mcg', 'Micrograms'), ('IU', 'International Units'), ('%', 'Daily Value Percentage')], default='mg', help_text='Unit of measurement for this nutrient', max_length=10, verbose_name='Measurement Unit')),
                ('nutritional_profile', models.ForeignKey(help_text='Associated nutritional profile', on_delete=django.db.models.deletion.CASCADE, to='core.nutritionalinfo', verbose_name='Nutritional Profile')),
            ],
            options={
                'verbose_name': 'Micronutrient Data',
                'verbose_name_plural': 'Micronutrients Data',
                'indexes': [models.Index(fields=['name'], name='core_additi_name_cbd6cb_idx')],
                'unique_together': {('nutritional_profile', 'name')},
            },
        ),
        migrations.AddConstraint(
            model_name='nutritionalinfo',
            constraint=models.UniqueConstraint(fields=('product_profile',), name='unique_nutritional_info_per_profile'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['collected_at'], name='core_produc_collect_27712c_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['stock_status'], name='core_produc_stock_s_ac2b73_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['store_product_link', 'collected_at'], name='core_produc_store_p_f30139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpricehistory',
            unique_together={('store_product_link', 'collected_at')},
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['external_id'], name='core_produc_externa_ae82e7_idx'),
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['store', 'product'], name='core_produc_store_i_e5d0b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstore',
            unique_together={('product', 'store'), ('store', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'name'], name='core_produc_brand_i_8b60c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'name')},
        ),
    ]
