# Generated by Django 6.0 on 2025-12-25 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Vitamin C, Iron', max_length=100, verbose_name='Nutrient Name')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%')], default='mg', max_length=10, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Micronutrient',
                'verbose_name_plural': 'Micronutrients',
            },
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="E.g. 'Saborizada' or 'Natural' - helps you identify this table in the admin.", max_length=200, verbose_name='Internal Label')),
                ('serving_size_grams', models.PositiveSmallIntegerField(verbose_name='Serving Size (g)')),
                ('energy_kcal', models.PositiveSmallIntegerField(verbose_name='Energy (kcal)')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Proteins (g)')),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carbs (g)')),
                ('total_sugars', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Total Sugars (g)')),
                ('added_sugars', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Added Sugars (g)')),
                ('total_fats', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Fats (g)')),
                ('saturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Saturated Fats (g)')),
                ('trans_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Trans Fats (g)')),
                ('dietary_fiber', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dietary Fiber (g)')),
                ('sodium', models.PositiveIntegerField(default=0, verbose_name='Sodium (mg)')),
            ],
            options={
                'verbose_name': 'Nutrition Facts',
                'verbose_name_plural': 'Nutrition Facts',
            },
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product Nutrition Profile',
                'verbose_name_plural': 'Product Nutrition Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='additionalnutrient',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='additionalnutrient',
            name='core_additi_name_cbd6cb_idx',
        ),
        migrations.RemoveConstraint(
            model_name='nutritionalinfo',
            name='unique_nutritional_info_per_profile',
        ),
        migrations.RemoveField(
            model_name='productnutritionprofile',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='productnutritionprofile',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productpricehistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productstore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Marketing description', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalproductpricehistory',
            name='collected_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Collection Timestamp'),
        ),
        migrations.AlterField(
            model_name='historicalproductpricehistory',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproductpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='historicalproductpricehistory',
            name='stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', max_length=1, verbose_name='Inventory Status'),
        ),
        migrations.AlterField(
            model_name='historicalproductpricehistory',
            name='store_product_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.productstore', verbose_name='Store Product Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(choices=[('REFILL', 'Refill Package'), ('CONTAINER', 'Container Package'), ('BAR', 'Bar'), ('OTHER', 'Other')], default='CONTAINER', max_length=20, verbose_name='Packaging Type'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Collection Timestamp'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='stock_status',
            field=models.CharField(choices=[('A', 'Available'), ('L', 'Last Units'), ('O', 'Out of Stock')], default='A', max_length=1, verbose_name='Inventory Status'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='store_product_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.productstore', verbose_name='Store Product Link'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='core.product', verbose_name='Related Product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'name', 'weight'), name='unique_product_brand_weight'),
        ),
        migrations.AddConstraint(
            model_name='productstore',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store'),
        ),
        migrations.AddConstraint(
            model_name='productstore',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('store', 'external_id'), name='unique_store_external_id'),
        ),
        migrations.AddField(
            model_name='micronutrient',
            name='nutrition_facts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micronutrients', to='core.nutritionfacts'),
        ),
        migrations.AddField(
            model_name='productnutrition',
            name='flavors',
            field=models.ManyToManyField(blank=True, to='core.flavor', verbose_name='Flavors'),
        ),
        migrations.AddField(
            model_name='productnutrition',
            name='nutrition_facts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_profiles', to='core.nutritionfacts', verbose_name='Nutrition Facts'),
        ),
        migrations.AddField(
            model_name='productnutrition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profiles', to='core.product', verbose_name='Base Product'),
        ),
        migrations.RemoveField(
            model_name='additionalnutrient',
            name='nutritional_profile',
        ),
        migrations.RemoveField(
            model_name='nutritionalinfo',
            name='product_profile',
        ),
        migrations.AddConstraint(
            model_name='micronutrient',
            constraint=models.UniqueConstraint(fields=('nutrition_facts', 'name'), name='unique_nutrient_per_facts'),
        ),
        migrations.AddConstraint(
            model_name='productnutrition',
            constraint=models.UniqueConstraint(fields=('product', 'nutrition_facts'), name='unique_product_nutrition_facts'),
        ),
        migrations.DeleteModel(
            name='AdditionalNutrient',
        ),
        migrations.DeleteModel(
            name='NutritionalInfo',
        ),
        migrations.DeleteModel(
            name='ProductNutritionProfile',
        ),
    ]
