# Generated by Django 6.0.3 on 2026-06-04 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Alert Subscriber',
                'verbose_name_plural': 'Alert Subscribers',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Who is this key for?', max_length=100, verbose_name='Client Name')),
                ('key', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Brand description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Unique category name', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Flavor description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Store description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Unique tag name', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Tag description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.CharField(blank=True, help_text="E.g. 'Saborizada' or 'Natural' to identify this table in the admin.", max_length=200, verbose_name='Internal Label')),
                ('serving_size_grams', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Serving Size (g)')),
                ('energy_kcal', models.PositiveSmallIntegerField(verbose_name='Energy (kcal)')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Proteins (g)')),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carbs (g)')),
                ('total_sugars', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Total Sugars (g)')),
                ('added_sugars', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Added Sugars (g)')),
                ('total_fats', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Fats (g)')),
                ('saturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Saturated Fats (g)')),
                ('trans_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Trans Fats (g)')),
                ('dietary_fiber', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dietary Fiber (g)')),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sodium (mg)')),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of nutritional values — used to suggest reuse in the admin', max_length=64, verbose_name='Content Hash')),
            ],
            options={
                'verbose_name': 'Nutrition Facts',
                'verbose_name_plural': 'Nutrition Facts',
                'constraints': [models.CheckConstraint(condition=models.Q(('serving_size_grams__gt', 0)), name='nutrition_facts_positive_serving_size')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(choices=[('SIMPLE', 'Simple Product'), ('COMBO', 'Combo/Kit')], default='SIMPLE', max_length=20, verbose_name='Product Type')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Marketing description', verbose_name='Description')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Total product weight in grams', null=True, verbose_name='Weight (grams)')),
                ('ean', models.CharField(blank=True, help_text='European Article Number / Global Trade Item Number', max_length=14, null=True, unique=True, verbose_name='EAN/GTIN')),
                ('packaging', models.CharField(choices=[('REFILL', 'Refill Package'), ('CONTAINER', 'Container Package'), ('BAR', 'Bar'), ('OTHER', 'Other')], default='CONTAINER', max_length=20, verbose_name='Packaging Type')),
                ('is_published', models.BooleanField(default=False, help_text='If checked, this product will be visible on the public website.', verbose_name='Published')),
                ('last_enriched_at', models.DateTimeField(blank=True, help_text='Timestamp of last content update by LLM agent', null=True, verbose_name='Last Enriched By LLM')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.product', verbose_name='Component Product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='core.product', verbose_name='Parent Combo')),
            ],
            options={
                'verbose_name': 'Product Component',
                'verbose_name_plural': 'Product Components',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='If this is a Combo, list the products it contains.', through='core.ProductComponent', to='core.product', verbose_name='Components'),
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('flavors', models.ManyToManyField(blank=True, to='core.flavor', verbose_name='Flavors')),
                ('nutrition_facts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_profiles', to='core.nutritionfacts', verbose_name='Nutrition Facts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profiles', to='core.product', verbose_name='Base Product')),
            ],
            options={
                'verbose_name': 'Product Nutrition Profile',
                'verbose_name_plural': 'Product Nutrition Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('affiliate_link', models.URLField(blank=True, default='', help_text='URL with affiliate tracking parameters', max_length=500, verbose_name='Affiliate Tracking URL')),
                ('offer', models.OneToOneField(blank=True, help_text='Merchant offer that holds the price series for this listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store', to='offers.offer', verbose_name='Merchant Offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='core.product', verbose_name='Related Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Associated Store')),
            ],
            options={
                'verbose_name': 'Store Product Link',
                'verbose_name_plural': 'Store Product Links',
                'ordering': ('store__name', 'product__name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, through='core.ProductStore', to='core.store', verbose_name='Available In Stores'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag', verbose_name='Product Tags'),
        ),
        migrations.CreateModel(
            name='Micronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='e.g., Vitamin C, Iron', max_length=100, verbose_name='Nutrient Name')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('-', '-'), ('g', 'g'), ('mg', 'mg'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%')], default='-', max_length=10, verbose_name='Unit')),
                ('nutrition_facts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micronutrients', to='core.nutritionfacts')),
            ],
            options={
                'verbose_name': 'Micronutrient',
                'verbose_name_plural': 'Micronutrients',
                'constraints': [models.UniqueConstraint(fields=('nutrition_facts', 'name'), name='unique_nutrient_per_facts')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('parent', 'component'), name='unique_product_component'),
        ),
        migrations.AddConstraint(
            model_name='productnutrition',
            constraint=models.UniqueConstraint(fields=('product', 'nutrition_facts'), name='unique_product_nutrition_facts'),
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['store', 'product'], name='core_produc_store_i_e5d0b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='productstore',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'name'], name='core_produc_brand_i_8b60c4_idx'),
        ),
    ]
