# Generated by Django 6.0.8 on 2026-09-15 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_mass', models.DecimalField(decimal_places=3, help_text='Mass of the active across every component, in the canonical unit.', max_digits=16, verbose_name='Total Mass')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_amounts', to='core.active', verbose_name='Active')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_actives', to='core.product', verbose_name='Combo')),
            ],
            options={
                'verbose_name': 'Combo Active',
                'verbose_name_plural': 'Combo Actives',
                'constraints': [models.UniqueConstraint(fields=('combo', 'active'), name='unique_combo_active')],
            },
        ),
    ]
