# Generated by Django 6.0.8 on 2026-09-16 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comboactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='product_component_quantity_positive'),
        ),
    ]
