# Generated by Django 6.0.8 on 2026-09-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_active_rankings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
