# Generated by Django 6.0.8 on 2026-09-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfacts',
            name='description',
            field=models.CharField(blank=True, help_text="E.g. 'Flavored' or 'Natural' to identify this table in the admin.", max_length=200, verbose_name='Internal Label'),
        ),
    ]
