# Generated by Django 6.0.8 on 2026-09-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productcomponent_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionactive',
            name='amount',
            field=models.DecimalField(decimal_places=3, help_text='As printed on the label, in the declared unit.', max_digits=16, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='added_sugars',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Added Sugars (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Carbs (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='dietary_fiber',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Dietary Fiber (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in kcal.', max_digits=10, null=True, verbose_name='Energy (kcal)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Proteins (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fats',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Saturated Fats (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Serving Size (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in mg.', max_digits=16, null=True, verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fats',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Total Fats (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_sugars',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Total Sugars (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='trans_fats',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Trans Fats (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_mass',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net content as printed on the package, in g.', max_digits=16, null=True, verbose_name='Net Mass (g)'),
        ),
    ]
