# Generated by Django 6.0.8 on 2026-09-07 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.text import slugify

#: Scalar nutrition columns promoted to actives, with the unit each is shown in.
LABEL_ACTIVES = (
    ("Protein", "g", "proteins"),
    ("Carbohydrates", "g", "carbohydrates"),
    ("Total Sugars", "g", "total_sugars"),
    ("Added Sugars", "g", "added_sugars"),
    ("Total Fats", "g", "total_fats"),
    ("Saturated Fats", "g", "saturated_fats"),
    ("Trans Fats", "g", "trans_fats"),
    ("Dietary Fiber", "g", "dietary_fiber"),
    ("Sodium", "mg", "sodium"),
)


def seed_label_actives(apps, schema_editor):
    """Seed the actives the nutrition label carries in its own columns."""
    active_model = apps.get_model("core", "Active")
    for name, unit, field in LABEL_ACTIVES:
        active_model.objects.get_or_create(
            slug=slugify(name),
            defaults={"name": name, "display_unit": unit, "nutrition_field": field},
        )


def drop_label_actives(apps, schema_editor):
    """Remove the seeded actives."""
    apps.get_model("core", "Active").objects.filter(
        slug__in=[slugify(name) for name, _unit, _field in LABEL_ACTIVES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_combo_kind_and_blank_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('display_unit', models.CharField(choices=[('-', '-'), ('g', 'g'), ('mg', 'mg'), ('mcg', 'mcg'), ('kg', 'kg'), ('kcal', 'kcal'), ('IU', 'IU'), ('%', '%')], default='g', help_text='Unit this active is presented in; storage stays canonical.', max_length=10, verbose_name='Display Unit')),
                ('nutrition_field', models.CharField(blank=True, choices=[('proteins', 'proteins'), ('carbohydrates', 'carbohydrates'), ('total_sugars', 'total_sugars'), ('added_sugars', 'added_sugars'), ('total_fats', 'total_fats'), ('saturated_fats', 'saturated_fats'), ('trans_fats', 'trans_fats'), ('dietary_fiber', 'dietary_fiber'), ('sodium', 'sodium')], default='', help_text='Scalar nutrition column carrying this active. Leave empty to read it from the nutrition active rows.', max_length=30, verbose_name='Nutrition Label Field')),
                ('description', models.TextField(blank=True, help_text='Active description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Active',
                'verbose_name_plural': 'Actives',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NutritionActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=3, help_text='Stored in the canonical unit of the declared dimension.', max_digits=16, verbose_name='Amount')),
                ('declared_unit', models.CharField(choices=[('-', '-'), ('g', 'g'), ('mg', 'mg'), ('mcg', 'mcg'), ('kg', 'kg'), ('kcal', 'kcal'), ('IU', 'IU'), ('%', '%')], default='-', help_text='Unit the printed label used, kept so it can be shown again.', max_length=10, verbose_name='Declared Unit')),
            ],
            options={
                'verbose_name': 'Nutrition Active',
                'verbose_name_plural': 'Nutrition Actives',
            },
        ),
        migrations.CreateModel(
            name='ProductActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fraction', models.DecimalField(decimal_places=8, help_text='Mass of the active per unit of product mass.', max_digits=12, verbose_name='Mass Fraction')),
            ],
            options={
                'verbose_name': 'Product Active',
                'verbose_name_plural': 'Product Actives',
                'ordering': ('product__name', 'active__name'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='micronutrient',
            name='unique_nutrient_per_facts',
        ),
        migrations.RemoveConstraint(
            model_name='nutritionfacts',
            name='nutrition_facts_positive_serving_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Energy'),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Serving Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_mass',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net content of the package, stored in the canonical unit.', max_digits=16, null=True, verbose_name='Net Mass'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='added_sugars',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Added Sugars'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Carbs'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='dietary_fiber',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Dietary Fiber'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Proteins'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fats',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Saturated Fats'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fats',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Total Fats'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_sugars',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Total Sugars'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='trans_fats',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True, verbose_name='Trans Fats'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfacts',
            constraint=models.CheckConstraint(condition=models.Q(('serving_size__gt', 0), ('serving_size__isnull', True), _connector='OR'), name='nutrition_facts_positive_serving_size'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_active',
            field=models.ForeignKey(blank=True, help_text='Active this category is ranked by when none is requested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='core.active', verbose_name='Default Active'),
        ),
        migrations.AddField(
            model_name='nutritionactive',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_amounts', to='core.active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='nutritionactive',
            name='nutrition_facts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='core.nutritionfacts'),
        ),
        migrations.AddField(
            model_name='productactive',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_amounts', to='core.active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='productactive',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='core.product', verbose_name='Product'),
        ),
        migrations.RemoveField(
            model_name='micronutrient',
            name='nutrition_facts',
        ),
        migrations.RemoveField(
            model_name='nutritionfacts',
            name='energy_kcal',
        ),
        migrations.RemoveField(
            model_name='nutritionfacts',
            name='serving_size_grams',
        ),
        migrations.AddConstraint(
            model_name='nutritionactive',
            constraint=models.UniqueConstraint(fields=('nutrition_facts', 'active'), name='unique_nutrient_per_facts'),
        ),
        migrations.AddIndex(
            model_name='productactive',
            index=models.Index(fields=['active', 'fraction'], name='core_produc_active__d94223_idx'),
        ),
        migrations.AddConstraint(
            model_name='productactive',
            constraint=models.UniqueConstraint(fields=('product', 'active'), name='unique_product_active'),
        ),
        migrations.DeleteModel(
            name='Micronutrient',
        ),
        migrations.RunPython(seed_label_actives, drop_label_actives),
    ]
