# Generated by Django 6.0.8 on 2026-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_label_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='scraper_slug',
            field=models.SlugField(blank=True, help_text="The store_slug the scraper records on this store's offers. Empty for a store nothing scrapes.", null=True, unique=True, verbose_name='Scraper Slug'),
        ),
    ]
