# Generated by Django 6.0.1 on 2026-02-01 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_productstore_affiliate_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "is_macro",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a macronutrient?",
                        verbose_name="Is Macro?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrient",
                "verbose_name_plural": "Nutrients",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="type",
            field=models.CharField(
                choices=[("SIMPLE", "Simple Product"), ("COMBO", "Combo/Kit")],
                default="SIMPLE",
                max_length=20,
                verbose_name="Product Type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("SIMPLE", "Simple Product"), ("COMBO", "Combo/Kit")],
                default="SIMPLE",
                max_length=20,
                verbose_name="Product Type",
            ),
        ),
        migrations.AddField(
            model_name="productnutrition",
            name="component_weight",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Weight contribution of this profile to the product/combo.",
                null=True,
                verbose_name="Component Weight (g)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="nutrient_sources",
            field=models.ManyToManyField(
                blank=True, to="core.nutrient", verbose_name="Nutrient Sources"
            ),
        ),
    ]
