# Generated by Django 6.0.8 on 2026-09-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_scraper_slug'),
        ('offers', '0004_offer_options_and_delist_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productstore',
            name='unique_product_store',
        ),
        migrations.AddField(
            model_name='productstore',
            name='nutrition_profile',
            field=models.ForeignKey(blank=True, help_text="The product's label that this offer's flavor prints. Required for a simple product, empty for a combo.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='core.productnutrition', verbose_name='Nutrition Profile'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='offer',
            field=models.OneToOneField(blank=True, help_text='The captured offer that prices this row. Its price, stock, URL and flavor come from the scraper; nothing about it is typed here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store', to='offers.offer', verbose_name='Merchant Offer'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(editable=False, help_text='Resolved from the offer; never chosen.', on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Associated Store'),
        ),
    ]
