# Generated by Django 6.0.8 on 2026-09-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_store_links_a_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_mass',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='As printed on the label, in g.', max_digits=16, null=True, verbose_name='Net Mass (g)'),
        ),
    ]
