# Generated by Django 6.0.8 on 2026-09-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_net_mass_label_field'),
        ('offers', '0004_offer_options_and_delist_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='offer',
            field=models.OneToOneField(blank=True, help_text='The captured offer that prices this row. Its price, stock, URL and flavor come from the scraper; nothing about it is typed here.', limit_choices_to={'delisted_at__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store', to='offers.offer', verbose_name='Merchant Offer'),
        ),
    ]
