# Generated by Django 6.0.8 on 2026-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_offer_choices_listed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productnutrition',
            name='unique_product_nutrition_facts',
        ),
        migrations.RemoveField(
            model_name='productstore',
            name='nutrition_profile',
        ),
        migrations.AddConstraint(
            model_name='productnutrition',
            constraint=models.UniqueConstraint(fields=('product',), name='one_nutrition_table_per_product'),
        ),
    ]
