# Generated by Django 6.0.8 on 2026-10-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('core', '0009_one_table_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller_account',
            field=models.OneToOneField(blank=True, help_text='The account this store sells through, in its own market.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_store', to='commerce.selleraccount', verbose_name='Seller Account'),
        ),
    ]
