# Generated by Django 6.0.3 on 2026-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_nutritionfacts_content_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrient_sources',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ('name',), 'verbose_name': 'Flavor', 'verbose_name_plural': 'Flavors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('brand__name', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productpricehistory',
            options={'get_latest_by': 'collected_at', 'ordering': ('-collected_at',), 'verbose_name': 'Price Tracking Record', 'verbose_name_plural': 'Price Tracking Records'},
        ),
        migrations.AlterModelOptions(
            name='productstore',
            options={'ordering': ('store__name', 'product__name'), 'verbose_name': 'Store Product Link', 'verbose_name_plural': 'Store Product Links'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',), 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='description',
            field=models.CharField(blank=True, help_text="E.g. 'Saborizada' or 'Natural' to identify this table in the admin.", max_length=200, verbose_name='Internal Label'),
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
    ]
