# Generated by Django 6.0.3 on 2026-04-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_micronutrient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Total product weight in grams', null=True, verbose_name='Weight (grams)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Total product weight in grams', null=True, verbose_name='Weight (grams)'),
        ),
    ]
