# Generated by Django 6.0.8 on 2026-10-04 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('offers', '0005_commercial_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('funder_raw', models.CharField(blank=True, help_text='Who pays for it, when stated; never inferred.', max_length=200, verbose_name='Funder')),
                ('source_key', models.CharField(help_text="The campaign's identity at its issuer; a code alone is not.", max_length=200, verbose_name='Source Key')),
                ('issuer_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='commerce.channel', verbose_name='Issuing channel')),
                ('issuer_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='commerce.program', verbose_name='Issuing programme')),
                ('issuer_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='commerce.selleraccount', verbose_name='Issuing seller')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PromotionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('informative', 'Informative'), ('executable', 'Executable'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='Status')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Starts At')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Exclusive. Empty means unknown, not forever.', null=True, verbose_name='Ends At')),
                ('timezone', models.CharField(help_text='The zone the issuer dates the campaign in.', max_length=64, verbose_name='Time Zone')),
                ('verified_at', models.DateTimeField(verbose_name='Verified At')),
                ('review_by', models.DateTimeField(blank=True, help_text='When the terms must be checked again.', null=True, verbose_name='Review By')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='A typed tree: {"root": null} or all/any/not over leaves.', verbose_name='Conditions')),
                ('ordering', models.JSONField(blank=True, default=list, help_text='Edges [{"before": 1, "after": 2}] between effect positions.', verbose_name='Effect Precedence')),
                ('limitations', models.TextField(blank=True, help_text='What the terms leave open: exclusions, stacking, dates.', verbose_name='Known Limitations')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Content Hash')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('currency', models.ForeignKey(help_text='The currency of every amount in these terms.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commerce.currency', verbose_name='Currency')),
                ('evidence', models.ManyToManyField(related_name='promotion_revisions', to='offers.evidence', verbose_name='Evidence')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='promotions.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Promotion Revision',
                'verbose_name_plural': 'Promotion Revisions',
                'ordering': ('promotion', '-number'),
            },
        ),
        migrations.CreateModel(
            name='PromotionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('position', models.PositiveSmallIntegerField(help_text='Names the effect in the precedence edges.', verbose_name='Position')),
                ('kind', models.CharField(choices=[('percentage', 'Percentage off'), ('fixed_amount', 'Amount off'), ('fixed_price', 'Fixed price'), ('shipping_discount', 'Shipping discount'), ('cashback', 'Cashback'), ('points', 'Points'), ('gift', 'Gift'), ('multibuy', 'Buy X pay Y'), ('tiered', 'Quantity tiers'), ('subscription', 'Subscription price')], max_length=20, verbose_name='Kind')),
                ('stage', models.CharField(choices=[('catalog', 'Catalog'), ('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('reward', 'Reward')], max_length=10, verbose_name='Stage')),
                ('basis', models.CharField(choices=[('initial', 'Initial price'), ('current', 'Price after earlier effects'), ('eligible_subtotal', 'Eligible subtotal'), ('order_total', 'Order total'), ('component', 'A component (shipping)')], max_length=20, verbose_name='Basis')),
                ('target', models.CharField(choices=[('item', 'Each item'), ('line', 'Each line'), ('group', 'A checkout group'), ('order', 'The order'), ('shipping', 'Shipping')], max_length=10, verbose_name='Target')),
                ('allocation', models.CharField(choices=[('per_unit', 'Per unit'), ('per_line', 'Per line'), ('once', 'Once'), ('prorated', 'Prorated over eligible lines')], max_length=10, verbose_name='Allocation')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('cap', models.DecimalField(blank=True, decimal_places=6, help_text="The most the effect gives, in the revision's currency.", max_digits=19, null=True, verbose_name='Cap')),
                ('max_applications', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Applications')),
                ('consumes_units', models.BooleanField(default=True, help_text='Units it uses cannot qualify another effect.', verbose_name='Consumes units')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='promotions.promotionrevision', verbose_name='Revision')),
            ],
            options={
                'verbose_name': 'Promotion Effect',
                'verbose_name_plural': 'Promotion Effects',
                'ordering': ('revision', 'position'),
            },
        ),
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('other_kind', models.CharField(choices=[('promotion', 'A promotion'), ('effect_kind', 'Any effect of a kind'), ('program', 'A programme'), ('payment_method', "A payment method's own discount")], max_length=15, verbose_name='About')),
                ('other_ref', models.CharField(help_text='A promotion id, an effect kind, a programme id or a method code.', max_length=100, verbose_name='Which')),
                ('verdict', models.CharField(choices=[('allowed', 'Allowed'), ('forbidden', 'Forbidden'), ('unknown', 'Unknown')], max_length=10, verbose_name='Verdict')),
                ('chooser', models.CharField(choices=[('store_imposed', 'The store'), ('buyer_choice', 'The buyer')], default='buyer_choice', max_length=15, verbose_name='Chooser')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compatibility_rules', to='offers.evidence', verbose_name='Evidence')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility', to='promotions.promotionrevision', verbose_name='Revision')),
            ],
            options={
                'verbose_name': 'Compatibility Rule',
                'verbose_name_plural': 'Compatibility Rules',
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('automatic', 'Automatic'), ('public_code', 'Public code'), ('personal_code', 'Personal code'), ('balance_redemption', 'Balance redemption'), ('required_action', 'Required action')], max_length=20, verbose_name='Kind')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Code')),
                ('channel_scope', models.CharField(choices=[('any', 'Any'), ('web', 'Web'), ('app', 'App')], default='any', max_length=10, verbose_name='Channel Scope')),
                ('instructions', models.CharField(blank=True, max_length=255, verbose_name='Instructions')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='promotions.promotionrevision', verbose_name='Revision')),
            ],
            options={
                'verbose_name': 'Activation Code',
                'verbose_name_plural': 'Activation Codes',
            },
        ),
        migrations.CreateModel(
            name='PromotionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(choices=[('qualification', 'Qualifies'), ('target', 'Receives the benefit')], max_length=15, verbose_name='Role')),
                ('mode', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], default='include', max_length=7, verbose_name='Mode')),
                ('kind', models.CharField(choices=[('channel', 'Channel'), ('market', 'Market'), ('seller_account', 'Seller account'), ('merchant', 'Merchant'), ('brand', 'Brand'), ('category', 'Category'), ('product', 'Product'), ('listing', 'Listing'), ('listing_variant', 'Listing variant'), ('offer', 'Offer'), ('external_category', 'Store category')], max_length=20, verbose_name='Kind')),
                ('ref_id', models.PositiveBigIntegerField(blank=True, help_text='The id of the named row.', null=True, verbose_name='Reference ID')),
                ('external_ref', models.CharField(blank=True, help_text='A store category name or id, verbatim.', max_length=200, verbose_name='External Reference')),
                ('combine', models.CharField(choices=[('union', 'Union'), ('intersection', 'Intersection')], default='union', help_text='How included rows of different kinds combine.', max_length=12, verbose_name='Combine')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='promotions.promotionrevision', verbose_name='Revision')),
            ],
            options={
                'verbose_name': 'Promotion Scope',
                'verbose_name_plural': 'Promotion Scopes',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('direct', 'Direct'), ('affiliate', 'Affiliate link'), ('cashback_activation', 'Cashback activation'), ('marketplace_listing', 'Marketplace listing')], max_length=20, verbose_name='Kind')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('fixes_variant', models.BooleanField(default=False, verbose_name='Opens the exact variant')),
                ('fixes_seller', models.BooleanField(default=False, verbose_name='Opens the exact seller')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('compatible_programs', models.ManyToManyField(blank=True, help_text='Programmes whose tracking survives this route; none by default.', related_name='compatible_routes', to='commerce.program', verbose_name='Compatible programmes')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_routes', to='offers.evidence', verbose_name='Evidence')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_routes', to='offers.listing', verbose_name='Listing')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_routes', to='offers.offer', verbose_name='Offer')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_routes', to='commerce.program', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Purchase Route',
                'verbose_name_plural': 'Purchase Routes',
            },
        ),
        migrations.CreateModel(
            name='RewardTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('credited_as', models.CharField(choices=[('money', 'Money'), ('restricted_credit', 'Restricted credit'), ('points', 'Points')], max_length=20, verbose_name='Credited As')),
                ('eligible_basis', models.CharField(choices=[('items_after_discounts', 'Items after discounts'), ('items_before_discounts', 'Items before discounts'), ('order_total', 'Order total')], default='items_after_discounts', help_text='Shipping is never in the basis unless the terms say so.', max_length=30, verbose_name='Eligible Basis')),
                ('includes_shipping', models.BooleanField(default=False, verbose_name='Includes shipping')),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Rate')),
                ('cap', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Cap')),
                ('cap_period', models.CharField(blank=True, choices=[('transaction', 'Per transaction'), ('month', 'Per month'), ('campaign', 'Per campaign')], max_length=12, verbose_name='Cap Period')),
                ('minimum', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Minimum Purchase')),
                ('tracking_required', models.BooleanField(default=False, verbose_name='Tracking required')),
                ('credit_delay_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit Delay (days)')),
                ('delay_from', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('delivery', 'Delivery'), ('confirmation', 'Confirmation'), ('statement', 'Card statement')], max_length=12, verbose_name='Delay Counted From')),
                ('expires_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expires After (days)')),
                ('redemption_minimum', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Redemption Minimum')),
                ('cancellation_terms', models.TextField(blank=True, verbose_name='Cancellation Terms')),
                ('effect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_terms', to='promotions.promotioneffect', verbose_name='Effect')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_terms', to='commerce.program', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Reward Terms',
                'verbose_name_plural': 'Reward Terms',
            },
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('issuer_seller__isnull', False), ('issuer_channel__isnull', False), ('issuer_program__isnull', False), _connector='OR'), name='promotion_has_an_issuer'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('issuer_seller', 'issuer_channel', 'issuer_program', 'source_key'), name='unique_promotion_per_issuer_source'),
        ),
        migrations.AddConstraint(
            model_name='promotionrevision',
            constraint=models.UniqueConstraint(fields=('promotion', 'number'), name='unique_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='promotionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='revision_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='promotionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='published_revision_has_a_date'),
        ),
        migrations.AddConstraint(
            model_name='promotioneffect',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='unique_effect_position'),
        ),
        migrations.AddConstraint(
            model_name='promotioneffect',
            constraint=models.CheckConstraint(condition=models.Q(('cap__isnull', True), ('cap__gte', 0), _connector='OR'), name='effect_cap_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='compatibilityrule',
            constraint=models.UniqueConstraint(fields=('revision', 'other_kind', 'other_ref'), name='one_rule_per_other'),
        ),
        migrations.AddConstraint(
            model_name='activationcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('public_code', 'personal_code')), _negated=True), models.Q(('code', ''), _negated=True), _connector='OR'), name='code_kind_has_a_code'),
        ),
        migrations.AddConstraint(
            model_name='promotionscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'external_category'), models.Q(('external_ref', ''), _negated=True)), models.Q(models.Q(('kind', 'external_category'), _negated=True), ('ref_id__isnull', False)), _connector='OR'), name='scope_names_its_row'),
        ),
        migrations.AddConstraint(
            model_name='purchaseroute',
            constraint=models.CheckConstraint(condition=models.Q(('offer__isnull', False), ('listing__isnull', False), _connector='OR'), name='route_names_offer_or_listing'),
        ),
        migrations.AddConstraint(
            model_name='rewardterms',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), models.Q(('rate__gt', 0), ('rate__lte', 100)), _connector='OR'), name='reward_rate_is_a_percentage'),
        ),
    ]
