# Generated by Django 5.2 on 2025-04-15 02:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the brand",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="CreatineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Creatine Type")),
            ],
            options={
                "verbose_name": "Creatine Type",
                "verbose_name_plural": "Creatine Types",
            },
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Flavor",
                "verbose_name_plural": "Flavors",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the store",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("PROTEIN", "Protein"), ("CREATINE", "Creatine")],
                        max_length=15,
                        verbose_name="Product Type",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "weight",
                    models.PositiveIntegerField(
                        help_text="Total weight in grams", verbose_name="Weight (g)"
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        choices=[("R", "Refill"), ("C", "Container")],
                        max_length=1,
                        verbose_name="Packaging",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.brand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="NutritionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serving_size_grams",
                    models.PositiveSmallIntegerField(verbose_name="Serving size (g)"),
                ),
                (
                    "energy_kcal",
                    models.PositiveSmallIntegerField(
                        verbose_name="Energy value (kcal)"
                    ),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Carbohydrates (g)"
                    ),
                ),
                (
                    "total_sugars",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Total sugars (g)"
                    ),
                ),
                (
                    "added_sugars",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Added sugars (g)"
                    ),
                ),
                (
                    "proteins",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Proteins (g)"
                    ),
                ),
                (
                    "total_fats",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Total fats (g)"
                    ),
                ),
                (
                    "saturated_fats",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="Saturated fats (g)",
                    ),
                ),
                (
                    "trans_fats",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Trans fats (g)"
                    ),
                ),
                (
                    "dietary_fiber",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Dietary fiber (g)"
                    ),
                ),
                ("sodium", models.PositiveIntegerField(verbose_name="Sodium (mg)")),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Other nutrients or additional information",
                        verbose_name="Complementary Information",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_infos",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutritional Information",
                "verbose_name_plural": "Nutritional Information",
            },
        ),
        migrations.CreateModel(
            name="CreatineInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creatine_types",
                    models.ManyToManyField(
                        related_name="creatine_products",
                        to="products.creatinetype",
                        verbose_name="Creatine Types",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatine_info",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creatine Information",
                "verbose_name_plural": "Creatine Information",
            },
        ),
        migrations.CreateModel(
            name="ProductFlavorNutritionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.flavor",
                        verbose_name="Flavor",
                    ),
                ),
                (
                    "nutritional_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.nutritionalinfo",
                        verbose_name="Nutritional Information",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flavor and Nutrition",
                "verbose_name_plural": "Flavors and Nutrition",
                "unique_together": {("product", "flavor")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="flavors",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductFlavorNutritionalInfo",
                to="products.flavor",
                verbose_name="Available Flavors",
            ),
        ),
        migrations.CreateModel(
            name="ProductStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affiliate_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Affiliate Link"
                    ),
                ),
                ("product_link", models.URLField(verbose_name="Product Link")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.store",
                        verbose_name="Store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Store Link",
                "verbose_name_plural": "Product Store Links",
                "unique_together": {("product", "store")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("L", "Last Units"),
                            ("O", "Out of Stock"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Stock Status",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Collected at"
                    ),
                ),
                ("history_change_reason", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_link",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.productstore",
                        verbose_name="Store Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "historical Price and Stock History",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProteinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=50, verbose_name="Protein Source"),
                ),
                (
                    "processing",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Processing Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protein Type",
                "verbose_name_plural": "Protein Types",
                "unique_together": {("source", "processing")},
            },
        ),
        migrations.CreateModel(
            name="ProteinInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protein_info",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "protein_types",
                    models.ManyToManyField(
                        related_name="protein_products",
                        to="products.proteintype",
                        verbose_name="Protein Types",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protein Information",
                "verbose_name_plural": "Protein Information",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="stores",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductStore",
                to="products.store",
                verbose_name="Available Stores",
            ),
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("L", "Last Units"),
                            ("O", "Out of Stock"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Stock Status",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Collected at"
                    ),
                ),
                (
                    "store_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.productstore",
                        verbose_name="Store Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price and Stock History",
                "verbose_name_plural": "Price and Stock History",
                "ordering": ["-collected_at"],
                "get_latest_by": "collected_at",
                "indexes": [
                    models.Index(
                        fields=["collected_at"], name="products_pr_collect_9165d0_idx"
                    ),
                    models.Index(
                        fields=["stock_status"], name="products_pr_stock_s_4ea363_idx"
                    ),
                ],
                "unique_together": {("store_link", "collected_at")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("brand", "name")},
        ),
    ]
