# Generated by Django 5.2 on 2025-04-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tag Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Tag Category",
                "verbose_name_plural": "Tag Categories",
            },
        ),
        migrations.RemoveField(
            model_name="creatineinfo",
            name="creatine_types",
        ),
        migrations.RemoveField(
            model_name="creatineinfo",
            name="product",
        ),
        migrations.RemoveField(
            model_name="proteininfo",
            name="product",
        ),
        migrations.RemoveField(
            model_name="proteininfo",
            name="protein_types",
        ),
        migrations.AlterUniqueTogether(
            name="proteintype",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="nutritionalinfo",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.CreateModel(
            name="AdditionalNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nutrient")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Value"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "grams"),
                            ("mg", "milligrams"),
                            ("mcg", "micrograms"),
                            ("IU", "international units"),
                            ("%", "percentage"),
                        ],
                        default="mg",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "nutritional_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_nutrients",
                        to="products.nutritionalinfo",
                        verbose_name="Nutritional Information",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Nutrient",
                "verbose_name_plural": "Additional Nutrients",
                "unique_together": {("nutritional_info", "name")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="products.tagcategory",
                verbose_name="Category",
            ),
        ),
        migrations.DeleteModel(
            name="CreatineType",
        ),
        migrations.DeleteModel(
            name="CreatineInfo",
        ),
        migrations.DeleteModel(
            name="ProteinInfo",
        ),
        migrations.DeleteModel(
            name="ProteinType",
        ),
    ]
