#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.14.14"
hooks = [
    { id = "ruff", args = ["--fix"] },
    { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/adamchainz/django-upgrade"
rev = "1.29.1"
hooks = [
    { id = "django-upgrade", args = ["--target-version", "6.0"] },
]

[[repos]]
repo = "https://github.com/riverside-healthcare/djlint"
rev = "v1.36.4"
hooks = [
    { id = "djlint-reformat-django" },
    { id = "djlint-django" },
]

[[repos]]
repo = "https://github.com/rtts/djhtml"
rev = "3.0.10"
hooks = [
    { id = "djhtml" },
]

[[repos]]
repo = "https://github.com/fpgmaas/deptry"
rev = "0.24.0"
hooks = [
    { id = "deptry", args = [".", "--config", "pyproject.toml"] },
]

[[repos]]
repo = "https://github.com/jendrikseipp/vulture"
rev = "v2.14"
hooks = [
    { id = "vulture", args = ["--config", "pyproject.toml"] },
]

[[repos]]
repo = "https://github.com/econchick/interrogate"
rev = "1.7.0"
hooks = [
    { id = "interrogate", args = ["-vv"] },
]
